#pragma once
#include <Core/Logging/LoggerFwd.hpp>

namespace Hyperion {

#pragma region Core

// Parent channel of all following in the region
CORE_API HYP_DECLARE_LOG_CHANNEL(Core);

CORE_API HYP_DECLARE_LOG_CHANNEL(Misc);
CORE_API HYP_DECLARE_LOG_CHANNEL(Temp);
CORE_API HYP_DECLARE_LOG_CHANNEL(Config);
CORE_API HYP_DECLARE_LOG_CHANNEL(Object);
CORE_API HYP_DECLARE_LOG_CHANNEL(Profile);
CORE_API HYP_DECLARE_LOG_CHANNEL(Math);
CORE_API HYP_DECLARE_LOG_CHANNEL(IO);
CORE_API HYP_DECLARE_LOG_CHANNEL(Net);
CORE_API HYP_DECLARE_LOG_CHANNEL(Threading);
CORE_API HYP_DECLARE_LOG_CHANNEL(Memory);

#pragma endregion Core

#pragma region Engine

ENGINE_API HYP_DECLARE_LOG_CHANNEL(Engine);

ENGINE_API HYP_DECLARE_LOG_CHANNEL(Perf);
ENGINE_API HYP_DECLARE_LOG_CHANNEL(DotNET);
ENGINE_API HYP_DECLARE_LOG_CHANNEL(Streaming);
ENGINE_API HYP_DECLARE_LOG_CHANNEL(UI);
ENGINE_API HYP_DECLARE_LOG_CHANNEL(Physics);
ENGINE_API HYP_DECLARE_LOG_CHANNEL(Audio);
ENGINE_API HYP_DECLARE_LOG_CHANNEL(Input);

#pragma endregion Engine

#pragma region Rendering

ENGINE_API HYP_DECLARE_LOG_CHANNEL(Rendering);

ENGINE_API HYP_DECLARE_LOG_CHANNEL(RenderingBackend);
ENGINE_API HYP_DECLARE_LOG_CHANNEL(RenderCommands);
ENGINE_API HYP_DECLARE_LOG_CHANNEL(Shader);
ENGINE_API HYP_DECLARE_LOG_CHANNEL(Texture);
ENGINE_API HYP_DECLARE_LOG_CHANNEL(Mesh);
ENGINE_API HYP_DECLARE_LOG_CHANNEL(Material);
ENGINE_API HYP_DECLARE_LOG_CHANNEL(Shadows);
ENGINE_API HYP_DECLARE_LOG_CHANNEL(EnvProbe);
ENGINE_API HYP_DECLARE_LOG_CHANNEL(Font);
ENGINE_API HYP_DECLARE_LOG_CHANNEL(Lightmap);

#pragma endregion Rendering

#pragma region Scene

ENGINE_API HYP_DECLARE_LOG_CHANNEL(Scene);

ENGINE_API HYP_DECLARE_LOG_CHANNEL(World);
ENGINE_API HYP_DECLARE_LOG_CHANNEL(Entity);
ENGINE_API HYP_DECLARE_LOG_CHANNEL(Node);
ENGINE_API HYP_DECLARE_LOG_CHANNEL(Camera);
ENGINE_API HYP_DECLARE_LOG_CHANNEL(Animation);

#pragma endregion Scene

#pragma region Assets

ENGINE_API HYP_DECLARE_LOG_CHANNEL(Assets);

ENGINE_API HYP_DECLARE_LOG_CHANNEL(Serialization);

#pragma endregion Assets

} // namespace Hyperion
