#include <Lang/HypScript.hpp>

#include <Lang/vm/BytecodeStream.hpp>

#include <Lang/compiler/emit/BytecodeChunk.hpp>
#include <Lang/compiler/emit/InstructionStream.hpp>
#include <Lang/compiler/emit/Instruction.hpp>
#include <Lang/compiler/emit/codegen/CodeGenerator.hpp>

#include <Lang/compiler/Module.hpp>
#include <Lang/compiler/SemanticAnalyzer.hpp>
#include <Lang/compiler/Optimizer.hpp>
#include <Lang/compiler/Lexer.hpp>
#include <Lang/compiler/Parser.hpp>
#include <Lang/compiler/Compiler.hpp>

#include <Lang/compiler/dis/DecompilationUnit.hpp>

#include <Lang/compiler/AstPrintVisitor.hpp>

#include <Lang/vm/VirtualMachine.hpp>

#include <Core/reflection/Class.hpp>
#include <Core/reflection/Method.hpp>
#include <Core/reflection/Field.hpp>
#include <Core/reflection/Member.hpp>
#include <Core/reflection/ClassRegistry.hpp>

#include <Core/io/ByteReader.hpp>

#include <Core/logging/Logger.hpp>
#include <Core/logging/LogChannels.hpp>

#include <Core/utilities/Format.hpp>
#include <Core/utilities/Result.hpp>

#include <iostream>

namespace Hyperion {

// #define HYP_PRINT_AST

HYP_DEFINE_LOG_CHANNEL(HypScript);

#include <Core/reflection/ScriptObjectFunctions.hpp>

static constexpr size_t ScriptPoolBlockSize = 8 * 1024 * 1024;

static Pool s_scriptPoolInstance { ScriptPoolBlockSize };
Pool* g_scriptPool = &s_scriptPoolInstance;

static struct HypScriptPoolDependencyInject
{
    HypScriptPoolDependencyInject()
    {
        ScriptObjectFunctions::GetScriptPool = []() -> Pool* {
            return g_scriptPool;
        };
    }
} s_hypScriptPoolDependencyInject {};

#pragma region HypScriptImpl

struct HypScriptImpl
{
    CompilationUnit* globalCompilationUnit;
    VirtualMachine* vm;
    Array<ScriptInstance*> aliveInstances;

    HypScriptImpl()
        : globalCompilationUnit(nullptr),
          vm(nullptr)
    {
    }

    HypScriptImpl(const HypScriptImpl& other) = delete;
    HypScriptImpl& operator=(const HypScriptImpl& other) = delete;

    void Initialize()
    {
        if (!globalCompilationUnit)
        {
            globalCompilationUnit = new CompilationUnit();
        }

        if (!vm)
        {
            vm = new VirtualMachine();
        }
    }

    void Shutdown()
    {
        delete globalCompilationUnit;
        globalCompilationUnit = nullptr;

        delete vm;
        vm = nullptr;
    }
};

#pragma endregion HypScriptImpl

namespace HypScript {

static HypScriptImpl s_impl;

/// Initialize the `Lib` script which is used to call into HypScript code from C++.
static Result InitializeHypScriptLib()
{
    // create the global script instance using Lib.hyp (generated by the CodeGen tool)
    static const FilePath s_libPath = CoreApi::GetExecutablePath() / "Lib.hyp";

    FileByteReader stream { s_libPath };
    if (stream.Eof())
    {
        return HYP_MAKE_ERROR(Error, "Failed to open Lib.hyp at path '{}'! Did the build tool run correctly?", s_libPath);
    }

    ByteBuffer byteBuffer = stream.Read();
    stream.Close();

    SourceFile sourceFile(s_libPath, byteBuffer.Size());
    sourceFile.ReadIntoBuffer(byteBuffer);

    ErrorList errorList;

    ScriptInstance* instance = Compile(sourceFile, errorList);

    if (errorList.HasFatalErrors())
    {
        return HYP_MAKE_ERROR(Error, "Failed to compile Lib.hyp! The script system will not function correctly.");
    }

    Assert(instance != nullptr);

    // run the main script to initialize classes, functions, etc.
    Run(instance);

    return {};
}

VirtualMachine* GetVM()
{
    return s_impl.vm;
}

void Initialize()
{
    s_impl.Initialize();

    Assert(s_impl.globalCompilationUnit != nullptr);
    BuiltinTypes::Initialize(s_impl.globalCompilationUnit);
}

void Shutdown()
{
    s_impl.Shutdown();
}

void DestroyScript(ScriptInstance* instance)
{
    if (!instance)
    {
        return;
    }

    auto it = s_impl.aliveInstances.Find(instance);
    if (it != s_impl.aliveInstances.End())
    {
        s_impl.aliveInstances.Erase(it);
    }

    delete instance;
}

HYP_NODISCARD ScriptInstance* Compile(
    SourceFile& sourceFile,
    ErrorList& outErrorList,
    const HypScriptCompileParams& params)
{
    if (!sourceFile.IsValid())
    {
        return nullptr;
    }

    SourceStream sourceStream(&sourceFile);
    TokenStream tokenStream(TokenStreamInfo { sourceFile.GetFilePath() });

    CompilationUnit compilationUnit;

    const FilePath basePath = sourceFile.GetFilePath().BasePath();

    // allow resolution of local modules
    compilationUnit.GetGlobalModule()->AddScanPath(basePath);
    // add local path as well
    compilationUnit.GetGlobalModule()->AddScanPath(CoreApi::GetExecutablePath());

    for (const FilePath& scanPath : params.scanPaths)
    {
        compilationUnit.GetGlobalModule()->AddScanPath(scanPath);
    }

    BuiltinTypes::RegisterTypes(&compilationUnit);

    Lexer lex(sourceStream, &tokenStream, &compilationUnit);
    lex.Analyze();

    AstIterator astIterator;
    SemanticAnalyzer semanticAnalyzer(&astIterator, &compilationUnit);

    Parser parser(&astIterator, &tokenStream, &compilationUnit);
    parser.Parse();

    astIterator.ResetPosition();
    semanticAnalyzer.Analyze();

#ifdef HYP_PRINT_AST
    AstPrintVisitor printer(&astIterator, &compilationUnit);
    printer.SetUseColors(true);
    printer.SetShowDetails(true);
    printer.SetShowLocations(true);
    printer.SetShowTypes(true);

    astIterator.ResetPosition();
    HYP_LOG(HypScript, Info, "{}", printer.PrintTree(astIterator.Peek()));
#endif

    outErrorList = compilationUnit.GetErrorList();
    outErrorList.WriteOutput(std::cout);

    if (!outErrorList.HasFatalErrors())
    {
        // only optimize if there were no errors
        // before this point
        astIterator.ResetPosition();

        Optimizer optimizer(&astIterator, &compilationUnit);
        optimizer.Optimize();

        // compile into bytecode instructions
        astIterator.ResetPosition();

        Compiler compiler(&astIterator, &compilationUnit);
        BytecodeChunk bytecodeChunk;

        if (auto compileResult = compiler.Compile())
        {
            bytecodeChunk.Append(std::move(compileResult));
        }
        else
        {
            return nullptr;
        }

        BuildParams buildParams {};

        CodeGenerator codeGenerator(buildParams);
        codeGenerator.Visit(&bytecodeChunk);
        codeGenerator.Bake();

        ScriptInstance* scriptInstance = new ScriptInstance {
            BytecodeStream(codeGenerator.GetInternalByteStream().GetData())
        };

        s_impl.aliveInstances.PushBack(scriptInstance);

        return scriptInstance;
    }

    return nullptr;
}

HYP_NODISCARD ScriptInstance* CreateFromBytecode(ConstByteView view)
{
    if (view.Size() == 0)
    {
        return nullptr;
    }

    ScriptInstance* scriptInstance = new ScriptInstance {
        BytecodeStream(ByteBuffer(view))
    };

    s_impl.aliveInstances.PushBack(scriptInstance);

    return scriptInstance;
}

void WriteBytecodeToStream(ScriptInstance* instance, ByteWriter& stream)
{
    if (!instance)
    {
        return;
    }

    const size_t currPosition = instance->stream.Position();
    const size_t max = instance->stream.Size();

    if (currPosition >= max)
    {
        return;
    }

    const size_t count = max - currPosition;

    ubyte* buffer = new ubyte[count];
    instance->stream.ReadBytes(buffer, count);

    stream.Write(reinterpret_cast<const char*>(buffer), count);

    delete[] buffer;

    // rewind stream back to where it was
    instance->stream.Seek(currPosition);
}

void Run(ScriptInstance* instance)
{
    AssertDebug(instance != nullptr);

    if (!instance)
    {
        return;
    }

    s_impl.vm->Execute(instance);
}

void CollectGarbage()
{
    if (s_impl.vm == nullptr)
    {
        return;
    }

    s_impl.vm->CollectGarbage(s_impl.aliveInstances);
}

InstructionStream* Decompile(ScriptInstance* instance, std::ostream* os)
{
    if (!instance)
    {
        return nullptr;
    }

    return DecompilationUnit().Decompile(instance->stream, os);
}

BoxedValue CallFunctionArgV(ScriptInstance* instance, const BoxedValue& value, BoxedValue* args, uint8 numArgs)
{
    Assert(instance != nullptr);
    Assert(IsFunction(value));

    if (numArgs != 0)
    {
        Assert(args != nullptr);

        for (uint8 i = 0; i < numArgs; i++)
        {
            instance->thread.m_stack.Push(std::move(args[i]));
        }
    }

    // Create a reference since we know the lifetime of the function handle will exist longer than the call
    // and we don't want to move the underlying value
    ScriptObjectData data;
    data.type = ScriptObjectData::Type::Reference;
    data.valueRef = const_cast<BoxedValue*>(&value);

    s_impl.vm->InvokeNow(instance, MakeValue(data), numArgs);

    if (numArgs != 0)
    {
        instance->thread.m_stack.Pop(numArgs);
    }

    return std::move(instance->thread.GetRegisters()[0]);
}

void ReadLastReturnValue(ScriptInstance* instance, BoxedValue& outValue)
{
    Assert(instance != nullptr);

    outValue = ShallowCopy(instance->thread.m_regs[0], s_impl.vm->GetGC());
}

bool GetMember(ScriptInstance* instance, const BoxedValue& targetValue, const char* memberName, BoxedValue& outValue)
{
    outValue = BoxedValue();

    if (!targetValue.IsValid())
    {
        return false;
    }

    const Handle<ObjectBase>& object = GetObject(targetValue);

    if (!object)
    {
        return false;
    }

    const Class* cls = object.ptr->InstanceClass();
    Assert(cls != nullptr);

    IMember* member = cls->GetMember(StringHash(memberName));

    if (!member)
    {
        return false;
    }

    if (member->GetMemberType() == MemberType::Field)
    {
        Field* field = static_cast<Field*>(member);

        outValue = MakeValue(field->Get(targetValue));

        return true;
    }

    if (member->GetMemberType() == MemberType::Method)
    {
        Method* method = static_cast<Method*>(member);

        ScriptObjectData data;

        if (method->IsScriptFunction())
        {
            Assert(method->GetParameters().Size() <= UINT8_MAX);

            data.type = ScriptObjectData::Type::ScriptFunction;
            data.func.m_addr = method->GetScriptAddress();
            data.func.m_nargs = (uint8)method->GetParameters().Size();
            data.func.m_flags = (uint8)method->GetFlags();
        }
        else
        {
            data.type = ScriptObjectData::Type::NativeFunction;
            data.nativeFunc = method;
        }

        outValue = MakeValue(data);

        return true;
    }

    return false;
}

bool SetField(BoxedValue& targetValue, const char* memberName, BoxedValue&& value)
{
    if (!targetValue.IsValid())
    {
        return false;
    }

    const Handle<ObjectBase>& object = GetObject(targetValue);

    if (!object)
    {
        return false;
    }

    const Class* cls = object.ptr->InstanceClass();
    Assert(cls != nullptr);

    Field* field = cls->GetField(StringHash(memberName));

    if (!field)
    {
        return false;
    }

    field->Set(targetValue, std::move(value));

    return true;
}

bool GetFunctionHandle(ScriptInstance* instance, const char* name, BoxedValue& outValue)
{
    outValue = BoxedValue();

    BoxedValue* value;
    if (!instance->exportedSymbols.Find(HashCode::GetHashCode(name).Value(), value))
    {
        return false;
    }

    if (!IsFunction(*value))
    {
        return false;
    }

    outValue = *value;

    return true;
}

bool GetExportedValue(ScriptInstance* instance, const char* name, BoxedValue& outValue, bool getReference)
{
    outValue = BoxedValue();

    BoxedValue* value;
    if (!instance->exportedSymbols.Find(HashCode::GetHashCode(name).Value(), value))
    {
        return false;
    }

    Assert(value != nullptr);
    value = Deref(*value);

    if (getReference || ShouldValuePassByRef(*value))
    {
        outValue = MakeRef(value);

        return true;
    }

    outValue = *value;

    return true;
}

SymbolTable& GetExportedSymbols(ScriptInstance* instance)
{
    return instance->exportedSymbols;
}

} // namespace HypScript

} // namespace Hyperion
