file(MAKE_DIRECTORY "${CONFIG_DST_DIR}")
set(KNOWN_PLATFORMS IOS Android Windows Mac Linux)

file(GLOB JSON_FILES "${CONFIG_SRC_DIR}/*.json")

foreach(JSON_FILE ${JSON_FILES})
    get_filename_component(FILENAME ${JSON_FILE} NAME)

    set(IS_OTHER_PLATFORM FALSE)
    foreach(KP ${KNOWN_PLATFORMS})
        if(FILENAME MATCHES "\\.${KP}\\.json$" AND NOT KP STREQUAL PLATFORM)
            set(IS_OTHER_PLATFORM TRUE)
            break()
        endif()
    endforeach()

    if(IS_OTHER_PLATFORM)
        continue()
    endif()

    string(REGEX MATCH "\\.(${PLATFORM})\\.json$" IS_MY_PLATFORM ${FILENAME})
    if(IS_MY_PLATFORM)
        execute_process(COMMAND ${CMAKE_COMMAND} -E copy_if_different "${JSON_FILE}" "${CONFIG_DST_DIR}/${FILENAME}")
        continue()
    endif()

    string(REGEX REPLACE "\\.json$" ".${PLATFORM}.json" PLATFORM_FILENAME ${FILENAME})
    set(PLATFORM_PATH "${CONFIG_SRC_DIR}/${PLATFORM_FILENAME}")

    if(EXISTS "${PLATFORM_PATH}")
        execute_process(COMMAND ${CMAKE_COMMAND} -E copy_if_different "${PLATFORM_PATH}" "${CONFIG_DST_DIR}/${FILENAME}")
    else()
        execute_process(COMMAND ${CMAKE_COMMAND} -E copy_if_different "${JSON_FILE}" "${CONFIG_DST_DIR}/${FILENAME}")
    endif()
endforeach()

file(GLOB ITEMS "${CONFIG_SRC_DIR}/*")
foreach(ITEM ${ITEMS})
    get_filename_component(EXT ${ITEM} EXT)
    if(EXT STREQUAL ".json")
        continue()
    endif()
    get_filename_component(NAME ${ITEM} NAME)
    if(NOT EXISTS "${CONFIG_DST_DIR}/${NAME}")
        if(IS_DIRECTORY "${ITEM}")
            execute_process(COMMAND ${CMAKE_COMMAND} -E copy_directory "${ITEM}" "${CONFIG_DST_DIR}/${NAME}")
        else()
            execute_process(COMMAND ${CMAKE_COMMAND} -E copy_if_different "${ITEM}" "${CONFIG_DST_DIR}/${NAME}")
        endif()
    endif()
endforeach()
