#version 450

#extension GL_GOOGLE_include_directive : require
#extension GL_EXT_scalar_block_layout : require
#extension GL_EXT_nonuniform_qualifier : require

// #define PASSTHROUGH

layout(local_size_x = 8, local_size_y = 8, local_size_z = 1) in;

#ifndef OUTPUT_FORMAT
#if defined(OUTPUT_RGBA8)
#define OUTPUT_FORMAT rgba8
#define TEMPORAL_BLENDING_GAMMA_CORRECTION
#elif defined(OUTPUT_RGBA16F)
#define OUTPUT_FORMAT rgba16f
#elif defined(OUTPUT_RGBA32F)
#define OUTPUT_FORMAT rgba32f
#else
#define OUTPUT_FORMAT rgba8
// #define TEMPORAL_BLENDING_REVERSE_TONEMAP;//TEMPORAL_BLENDING_GAMMA_CORRECTION
#endif
#endif

HYP_DESCRIPTOR_SRV(TemporalBlending, InImage) uniform texture2D input_texture;
HYP_DESCRIPTOR_SRV(TemporalBlending, PrevImage) uniform texture2D prev_input_texture;
HYP_DESCRIPTOR_SRV(TemporalBlending, VelocityImage) uniform texture2D velocity_texture;
HYP_DESCRIPTOR_SAMPLER(TemporalBlending, SamplerLinear) uniform sampler sampler_linear;
HYP_DESCRIPTOR_SAMPLER(TemporalBlending, SamplerNearest) uniform sampler sampler_nearest;

HYP_DESCRIPTOR_UAV(TemporalBlending, OutImage, format = OUTPUT_FORMAT) uniform writeonly image2D output_image;

#ifndef TEMPORAL_BLEND_TECHNIQUE
#define TEMPORAL_BLEND_TECHNIQUE 0
#endif

#define HYP_DO_NOT_DEFINE_DESCRIPTOR_SETS
#include "./include/defines.inc"
#include "./include/packing.inc"
#include "./include/defines.inc"
#include "./include/packing.inc"
#include "./include/shared.inc"
#include "./include/scene.inc"

#define TEMPORAL_BLENDING_USE_YCoCg

//#define ADJUST_COLOR_HDR

#include "./include/Temporal.inc"
#undef HYP_DO_NOT_DEFINE_DESCRIPTOR_SETS

HYP_DESCRIPTOR_BUFFER(TemporalBlending, WorldsBuffer) uniform WorldsBuffer
{
    WorldShaderData world_shader_data;
};

HYP_DESCRIPTOR_BUFFER_DYNAMIC(TemporalBlending, CamerasBuffer) uniform CamerasBuffer
{
    Camera camera;
};

HYP_DESCRIPTOR_SRV(TemporalBlending, GBufferDepthTexture) uniform texture2D depth_texture;

HYP_DESCRIPTOR_BUFFER(TemporalBlending, TemporalBlendingUniforms) uniform TemporalBlendingUniforms
{
    uvec2 output_dimensions;
    uvec2 depth_texture_dimensions;
    uint blending_frame_counter;
    uint _pad0;
};

void main(void)
{
    const uvec2 coord = gl_GlobalInvocationID.xy;

    if (any(greaterThanEqual(coord, output_dimensions)))
    {
        return;
    }

    const vec2 uv = (vec2(coord) + 0.5) / vec2(output_dimensions);
    const vec2 texel_size = vec2(1.0) / vec2(output_dimensions);
    vec4 color;

    vec2 velocity;
    float view_space_depth;

    InitTemporalParams(
        depth_texture,
        velocity_texture,
        depth_texture_dimensions,
        uv,
        camera.near,
        camera.far,
        velocity,
        view_space_depth);

#ifdef PASSTHROUGH
    color = SAMPLE_TEXTURE_2D(sampler_nearest, input_texture, uv);
#elif TEMPORAL_BLEND_TECHNIQUE == 0
    color = RGBToYCoCg(ADJUST_COLOR_GAMMA_IN(SAMPLE_TEXTURE_2D(sampler_nearest, input_texture, uv)));
    vec4 previous_color = RGBToYCoCg(ADJUST_COLOR_GAMMA_IN(SAMPLE_TEXTURE_2D(sampler_linear, prev_input_texture, uv - velocity)));

    const float _SubpixelThreshold = 0.5;
    const float _GatherBase = 0.5;
    const float _GatherSubpixelMotion = 0.1666;

    const vec2 texel_vel = velocity / max(vec2(HYP_FMATH_EPSILON), texel_size);
    const float texel_vel_mag = length(texel_vel) * view_space_depth;
    const float subpixel_motion = saturate(_SubpixelThreshold / max(HYP_FMATH_EPSILON, texel_vel_mag));
    const float min_max_support = _GatherBase + _GatherSubpixelMotion * subpixel_motion;

    vec4 mean = color;
    vec4 stddev = color * color;

    const vec2 ss_offset01 = min_max_support * vec2(-texel_size.x, texel_size.y);
    const vec2 ss_offset11 = min_max_support * vec2(texel_size.x, texel_size.y);

    const vec2 offsets[4] = vec2[](
        -ss_offset11, // vec2(-1.0, 0.0),
        -ss_offset01, // vec2(1.0, 0.0),
        ss_offset01,  // vec2(0.0, -1.0),
        ss_offset11   // vec2(0.0, 1.0)
    );

    for (int i = 0; i < 4; i++)
    {
        vec4 c = RGBToYCoCg(ADJUST_COLOR_GAMMA_IN(SAMPLE_TEXTURE_2D(sampler_linear, input_texture, uv + offsets[i])));

        mean += c;
        stddev += c * c;
    }

    mean /= 5.0;
    stddev = sqrt(max(stddev / 5.0 - (mean * mean), 0.0));

    // Use a gamma factor to widen the AABB slightly, reducing flickering
    const float variance_gamma = 1.0;
    vec4 clipped = ClipToAABB(color, previous_color, mean, stddev * variance_gamma);

    color = TemporalLuminanceResolveYCoCg(color, clipped);
    color = YCoCgToRGB(color);
    color = ADJUST_COLOR_GAMMA_OUT(color);

    color = any(isnan(color)) ? vec4(0.0, 0.0, 1.0, 1.0) : color;

#elif TEMPORAL_BLEND_TECHNIQUE == 1
    color = TemporalResolve(input_texture, prev_input_texture, uv, velocity, texel_size, view_space_depth);

#elif TEMPORAL_BLEND_TECHNIQUE == 2
    color = TemporalBlendRounded(input_texture, prev_input_texture, uv, velocity, texel_size, view_space_depth);
#elif TEMPORAL_BLEND_TECHNIQUE == 3
    color = TemporalBlendVarying(input_texture, prev_input_texture, uv, velocity, texel_size, view_space_depth);
#elif TEMPORAL_BLEND_TECHNIQUE == 4
    color = SAMPLE_TEXTURE_2D(sampler_nearest, input_texture, uv);
    vec4 previous_color = SAMPLE_TEXTURE_2D(sampler_linear, prev_input_texture, uv);

    // Moving average over number of frames
    if (blending_frame_counter > 0)
    {
        float alpha = 1.0 / float(blending_frame_counter + 1);
        color = mix(previous_color, color, alpha);
    }
    
    color.a = 1.0;
#endif

    imageStore(output_image, clamp(ivec2(coord), ivec2(0), ivec2(output_dimensions) - 1), color);
}
