[DeferredIndirect]
versions = SSGI_ENABLED, RT_REFLECTIONS, RT_GI, HBIL_ENABLED, HBAO_EABLED
frag = DeferredIndirect.frag
vert = Deferred.vert

[DeferredDirect]
versions = LIGHT_TYPE(DIRECTIONAL POINT SPOT AREA_RECT)
frag = DeferredDirect.frag
vert = Deferred.vert

[ApplyReflectionProbe]
versions = ENV_PROBE_PARALLAX_CORRECTED
frag = deferred/ApplyReflectionProbe.frag
vert = Deferred.vert

[ApplyLightmap]
frag = deferred/ApplyLightmap.frag
vert = Deferred.vert

[ApplyFogVolume]
frag = deferred/ApplyFogVolume.frag
vert = deferred/ApplyFogVolume.vert

[Tonemap]
versions = OUTPUT(PQ_HDR SDR)
frag = Tonemap.frag
vert = PostEffect.vert

[FXAA]
frag = FXAA.frag
vert = PostEffect.vert

[DOFBlurDirection]
versions = DIRECTION(HORIZONTAL VERTICAL)
frag = dof/DOFBlurDirection.frag
vert = PostEffect.vert

[DOFBlurMix]
frag = dof/DOFBlurMix.frag
vert = PostEffect.vert

[ObjectVisibility]
versions = INSTANCING
comp = OcclusionCulling/OcclusionCulling.comp

[GenerateDepthPyramid]
comp = OcclusionCulling/GenerateDepthPyramid.comp

[GenerateMipmaps]
vert = PostEffect.vert
frag = GenerateMipmaps.frag

[RenderTextureToScreen]
versions = HALFRES
frag = RenderTextureToScreen.frag
vert = PostEffect.vert

[MergeHalfResTextures]
frag = MergeHalfResTextures.frag
vert = PostEffect.vert

[RenderToCubemap]
versions = HAS_ALBEDO_MAP, MODE_SHADOWS, WRITE_NORMALS, WRITE_MOMENTS, INSTANCING, ENV_PROBE, SKINNING
frag = RenderToCubemap.frag
vert = RenderToCubemap.vert

[RenderSky]
frag = sky/RenderSky.frag
vert = sky/RenderSky.vert

[ComputeSH]
versions = MODE(CLEAR BUILD_COEFFICIENTS REDUCE FINALIZE), LIGHTING
comp = env_probe/ComputeSH.comp

[ConvolveProbe]
versions = NUM_SAMPLES(16 32 64 128), LOBE_SIZE(0.9 0.94 0.98)
comp = env_probe/ConvolveProbe.comp

[GeometryPass]
versions = SKINNING, ALPHA_DISCARD, INSTANCING, SHADING_TYPE(DEFERRED FORWARD UNLIT LIGHTMAPPED), HAS_ALBEDO_MAP, HAS_NORMAL_MAP, HAS_PARALLAX_MAP, HAS_METALNESS_MAP, HAS_ROUGHNESS_MAP, HAS_AO_MAP
frag = GeometryPass.frag
vert = Default.vert

[Vegetation]
frag = GeometryPass.frag
vert = Vegetation.vert

[Skybox]
versions = INSTANCING
frag = Skybox.frag
vert = Skybox.vert

[Terrain]
versions = INSTANCING
frag = Terrain.frag
vert = Default.vert

[HBAO]
versions = HBIL_ENABLED, HALFRES
frag = hbao/HBAO.frag
vert = PostEffect.vert

[Particle]
frag = particles/Particle.frag
vert = particles/Particle.vert

[UpdateParticles]
versions = HAS_PHYSICS
comp = particles/UpdateParticles.comp

[Shadows]
versions = MODE(STANDARD VSM PCF CONTACT_HARDENED), INSTANCING, SKINNING, ALPHA_DISCARD
frag = shadow.frag
vert = Default.vert

[BlurShadowMap]
comp = shadow/BlurShadowMap.comp

[CombineShadowMaps]
versions = VSM
frag = shadow/CombineShadowMaps.frag
vert = PostEffect.vert

[SSRWriteUVs]
versions = CONE_TRACING, ROUGHNESS_SCATTERING
vert = PostEffect.vert
frag = ssr/SSRWriteUVs.frag

[SSRSampleGBuffer]
versions = CONE_TRACING
vert = PostEffect.vert
frag = ssr/SSRSampleGBuffer.frag

[SSGI]
versions = OUTPUT(RGBA8 RGBA16F RGBA32F)
comp = ssr/SSGI.comp

[UIObject]
versions = TEXTURED
frag = ui/UIObject.frag
vert = ui/UIObject.vert

[DebugAABB]
versions = IMMEDIATE_MODE, INSTANCING
frag = DebugAABB.frag
vert = DebugAABB.vert

# RT

[RTRadiance]
versions = HAS_ENV_PROBE
rgen = rt/RTRadiance.rgen
rchit = rt/RTRadiance.rchit
rmiss = rt/RTRadiance.rmiss

[PathTracer]
rgen = rt/pathtracer/PathTracer.rgen
rchit = rt/pathtracer/PathTracer.rchit
rmiss = rt/pathtracer/PathTracer.rmiss

[LightmapPathTracer]
versions = MODE(IRRADIANCE RADIANCE FULL)
rgen = rt/lightmapper/LightmapPathTracer.rgen
rchit = rt/lightmapper/LightmapPathTracer.rchit
rmiss = rt/lightmapper/LightmapPathTracer.rmiss

[DDGI]
versions = HAS_ENV_PROBE
rgen = rt/gi/DDGI.rgen
rchit = rt/gi/DDGI.rchit
rmiss = rt/gi/DDGI.rmiss

[RTCopyBorderTexelsIrradiance]
comp = rt/copy_border_texels_irradiance.comp

[RTCopyBorderTexelsDepth]
comp = rt/copy_border_texels_depth.comp

[RTProbeUpdateIrradiance]
comp = rt/probe_update_irradiance.comp

[RTProbeUpdateDepth]
comp = rt/probe_update_depth.comp

# Temporal

[TemporalAA]
comp = TemporalAA.comp

[TemporalBlending]
versions = OUTPUT(RGBA8 RGBA16F RGBA32F), TEMPORAL_BLEND_TECHNIQUE(0 1 2 3 4)
comp = TemporalBlending.comp

[ImageBlurCompute]
versions = HORIZONTAL, OUTPUT(RGBA8 RGBA16F RGBA32F)
comp = Blur.comp

# Lightmapping
[DilateLightmap]
comp = lightmapping/DilateLightmap.comp.glsl

# Third Party Shaders

[FfxParallelSort_Reduce]
entry_point = FfxParallelSortReduce
comp = third_party/FfxParallelSort.hlsl

[FfxParallelSort_ScanAdd]
entry_point = FfxParallelSortScanAdd
comp = third_party/FfxParallelSort.hlsl

[FfxParallelSort_Scan]
entry_point = FfxParallelSortScan
comp = third_party/FfxParallelSort.hlsl

[FfxParallelSort_Scatter]
entry_point = FfxParallelSortScatter
comp = third_party/FfxParallelSort.hlsl

[FfxParallelSort_Count]
entry_point = FfxParallelSortCount
comp = third_party/FfxParallelSort.hlsl

# Testing

[TestHLSL]
vert = TestHLSL.hlsl