#include <Core/CLI/CommandLine.hpp>

#include <Core/Logging/Logger.hpp>

#include <Core/FileSystem/FilePath.hpp>

#include <Core/Utilities/DeferredScope.hpp>

#include <Core/Threading/Thread.hpp>
#include <Core/Threading/Scheduler.hpp>
#include <Core/Threading/AtomicVar.hpp>
#include <Core/Threading/TaskSystem.hpp>
#include <Core/Threading/TaskThread.hpp>
#include <Core/Threading/Mutex.hpp>

#include <Core/IO/ByteWriter.hpp>
#include <Core/IO/BufferedByteReader.hpp>

#include <Core/Utilities/StringUtil.hpp>

#include <Core/Functional/Proc.hpp>

#include <Core/Memory/UniquePtr.hpp>

#include <generator/generators/CXXModuleGenerator.hpp>
#include <generator/generators/CSharpModuleGenerator.hpp>
#include <generator/generators/HypScriptModuleGenerator.hpp>

#include <parser/Parser.hpp>

#include <analyzer/Analyzer.hpp>

#include <Util/Util.hpp>

#if !defined(HYP_CODEGEN_VERSION_MAJOR) || !defined(HYP_CODEGEN_VERSION_MINOR) || !defined(HYP_CODEGEN_VERSION_PATCH)
#error "HYP_CODEGEN_VERSION_MAJOR, HYP_CODEGEN_VERSION_MINOR, and HYP_CODEGEN_VERSION_PATCH must be defined"
#endif

namespace Hyperion {
namespace CodeGen {

HYP_DEFINE_LOG_CHANNEL(Tool);

static constexpr bool JumboBuildEnabled = true;
static constexpr uint32 JumboBuildIdealFileSize = 64 * 1024;

static const String s_hypscriptPreamble = R"(// This file is autogenerated. Do not edit.

const INT8_MAX : int8 = 0x7F
const INT16_MAX : int16 = 0x7FFF
const INT32_MAX : int32 = 0x7FFFFFFF
const INT64_MAX : int64 = 0x7FFFFFFFFFFFFFFF
const UINT8_MAX : uint8 = 0xFFu
const UINT16_MAX : uint16 = 0xFFFFu
const UINT32_MAX : uint32 = 0xFFFFFFFFu
const UINT64_MAX : uint64 = 0xFFFFFFFFFFFFFFFFu
const FLT_MAX : float = 3.40282347e+38F
const FLT_MIN : float = 1.17549435e-38F
const FLT_EPSILON : float = 1.19209290e-07F
const DBL_MAX : double = 1.7976931348623157e+308
const DBL_MIN : double = 2.2250738585072014e-308
const DBL_EPSILON : double = 2.2204460492503131e-16

)";

class WorkerThread : public TaskThread
{
public:
    WorkerThread(ThreadId id)
        : TaskThread(id)
    {
    }

    virtual ~WorkerThread() override = default;
};

class WorkerThreadPool : public TaskThreadPool
{
public:
    WorkerThreadPool()
        : TaskThreadPool(TypeWrapper<WorkerThread>(), "BuildTool_WorkerThread", 4)
    {
    }

    virtual ~WorkerThreadPool() override = default;
};

class Tool
{
public:
    enum class CXXGenerationMode
    {
        CPP,
        INL
    };

    Tool(
        const FilePath& workingDirectory,
        const FilePath& sourceDirectory,
        const FilePath& cxxOutputDirectory,
        const FilePath& csharpOutputDirectory,
        const FilePath& hypscriptOutputDirectory,
        const Set<FilePath>& excludeDirectories,
        const Set<FilePath>& excludeFiles,
        CXXGenerationMode cxxMode = CXXGenerationMode::CPP)
    {
        m_analyzer.SetWorkingDirectory(workingDirectory);
        m_analyzer.SetSourceDirectory(sourceDirectory);

        m_analyzer.SetCXXOutputDirectory(cxxOutputDirectory);
        m_analyzer.SetCSharpOutputDirectory(csharpOutputDirectory);
        m_analyzer.SetHypScriptOutputDirectory(hypscriptOutputDirectory);

        m_analyzer.SetExcludeDirectories(excludeDirectories);
        m_analyzer.SetExcludeFiles(excludeFiles);

        m_analyzer.SetGlobalDefines(GetGlobalDefines());
        m_analyzer.SetIncludePaths(GetIncludePaths());

        m_cxxMode = cxxMode;

        m_threadPool.Start();
    }

    ~Tool()
    {
        m_threadPool.Stop();
    }

    Result Run()
    {
        HYP_LOG(Tool, Info, "Hyperion CodeGen v{}.{}.{}", HYP_CODEGEN_VERSION_MAJOR, HYP_CODEGEN_VERSION_MINOR, HYP_CODEGEN_VERSION_PATCH);
        HYP_LOG(Tool, Info, "Running...");

        FindModules();

        Task processModules = ProcessModules();
        WaitWhileTaskRunning(processModules);

        Task buildClassTree = BuildClassTree();
        WaitWhileTaskRunning(buildClassTree);

        Task generateOutputFiles = GenerateOutputFiles();
        WaitWhileTaskRunning(generateOutputFiles);

        if (m_analyzer.GetState().HasErrors())
        {
            for (const AnalyzerError& error : m_analyzer.GetState().errors)
            {
                HYP_LOG(Tool, Error, "Error: {}", error.GetMessage());
            }

            return HYP_MAKE_ERROR(Error, "CodeGen failed with {} error(s)", m_analyzer.GetState().errors.Size());
        }

        // finally, add CodeGenOutput.inc to the output directory
        FilePath outputFilePath = m_analyzer.GetCXXOutputDirectory() / "CodeGenOutput.inc";
        FileByteWriter outputFileWriter(outputFilePath);
        if (!outputFileWriter.IsOpen())
        {
            return HYP_MAKE_ERROR(Error, "Failed to open output file: {}", outputFilePath);
        }

        // for parsing from scripts to enable rebuild triggering:
        outputFileWriter.WriteString("//! VERSION " + String::ToString(HYP_CODEGEN_VERSION_MAJOR) + "." + String::ToString(HYP_CODEGEN_VERSION_MINOR) + "." + String::ToString(HYP_CODEGEN_VERSION_PATCH) + "\n\n");
        outputFileWriter.WriteString("// This file is generated by the Hyperion CodeGen. Do not edit manually.\n\n");
        outputFileWriter.WriteString("#pragma once\n\n");
        outputFileWriter.WriteString("#define HYP_CODEGEN_VERSION_MAJOR " + String::ToString(HYP_CODEGEN_VERSION_MAJOR) + "\n");
        outputFileWriter.WriteString("#define HYP_CODEGEN_VERSION_MINOR " + String::ToString(HYP_CODEGEN_VERSION_MINOR) + "\n");
        outputFileWriter.WriteString("#define HYP_CODEGEN_VERSION_PATCH " + String::ToString(HYP_CODEGEN_VERSION_PATCH) + "\n\n");

        outputFileWriter.WriteString("\n");
        outputFileWriter.Close();

        HYP_LOG(Tool, Info, "CodeGen completed successfully");

        return {};
    }

private:
    Map<String, String> GetGlobalDefines() const
    {
        return {
            { "HYP_TOOL", "1" },
            { "HYP_VULKAN", "1" },
            { "HYP_CLASS(...)", "" },
            { "HYP_STRUCT(...)", "" },
            { "HYP_ENUM(...)", "" },
            { "HYP_FIELD(...)", "" },
            { "HYP_METHOD(...)", "" },
            { "HYP_PROPERTY(...)", "" },
            { "HYP_OBJECT_BODY(...)", "" },
            { "ENGINE_API", "" },
            { "CORE_API", "" },
            { "EDITOR_API", "" },
            { "RENDERING_API", "" },
            { "HYP_EXPORT", "" },
            { "HYP_IMPORT", "" },
            { "HYP_FORCE_INLINE", "inline" },
            { "HYP_NODISCARD", "" }
        };
    }

    Set<String> GetIncludePaths() const
    {
        const FilePath& workingDirectory = m_analyzer.GetWorkingDirectory();

        return {
            workingDirectory / "Source/Engine",
            workingDirectory / "include"
        };
    }

    void FindModules()
    {
        Proc<void(const FilePath&)> iterateFilesAndSubdirectories;

        iterateFilesAndSubdirectories = [&](const FilePath& dir)
        {
            for (const String& excludeDir : m_analyzer.GetExcludeDirectories())
            {
                const FilePath relativePath = FilePath(FileSystem::RelativePath(dir.Data(), m_analyzer.GetSourceDirectory().Data()).c_str());

                if (relativePath.StartsWith(excludeDir))
                {
                    return;
                }
            }

            Array<Module*> localModules;

            for (const FilePath& file : dir.GetAllFilesInDirectory())
            {
                if (file.EndsWith(".hpp"))
                {
                    const FilePath relativePath = FilePath(FileSystem::RelativePath(file.Data(), m_analyzer.GetSourceDirectory().Data()).c_str());

                    if (m_analyzer.GetExcludeFiles().Contains(relativePath))
                    {
                        continue;
                    }

                    localModules.PushBack(m_analyzer.AddModule(file));
                }
            }

            Array<FilePath> localSubdirectories = dir.GetSubdirectories();

            if (localSubdirectories.Empty())
            {
                return;
            }

            for (const FilePath& subdirectory : localSubdirectories)
            {
                iterateFilesAndSubdirectories(subdirectory);
            }
        };

        iterateFilesAndSubdirectories(m_analyzer.GetSourceDirectory());
    }

    Task<void> ProcessModules()
    {
        Task<void> task;

        TaskBatch* batch = new TaskBatch();
        batch->pool = &m_threadPool;
        batch->OnComplete
            .Bind([batch, promise = task.Promise()]()
                {
                    promise->Fulfill();

                    DeferDeleteTaskBatch(batch);
                })
            .Detach();

        for (const UniquePtr<Module>& mod : m_analyzer.GetModules())
        {
            batch->AddTask([this, mod = mod.Get()]()
                {
                    auto result = m_analyzer.ProcessModule(*mod);

                    if (result.HasError())
                    {
                        m_analyzer.AddError(result.GetError());

                        return;
                    }
                });
        }

        TaskSystem::GetInstance().EnqueueBatch(batch);

        return task;
    }

    Task<void> BuildClassTree()
    {
        return TaskSystem::GetInstance().Enqueue([this]()
            {
                Array<ClassDefinition*> classDefinitions;
                Map<String, uint32> classDefinitionIds;

                for (auto& it : m_analyzer.GetBuiltinClasses())
                {
                    if (classDefinitionIds.Contains(it.second.name))
                    {
                        m_analyzer.AddError(HYP_MAKE_ERROR(AnalyzerError, "Duplicate ClassDefinition name found: {}", "<builtin>", 0, it.second.name));

                        continue;
                    }

                    Assert(it.second.staticIndex != -1); // builtins should have static indices assigned

                    const uint32 classDefinitionId = uint32(classDefinitions.Size());

                    classDefinitionIds[it.second.name] = classDefinitionId;
                    classDefinitions.PushBack(&it.second);
                }

                // @FIXME ObjectBase decl needs to go in Core/ClassDecls.cpp not main engine one
                auto objectBaseIt = classDefinitions.FindIf([](const ClassDefinition* classDef)
                    {
                        return classDef->name == "ObjectBase";
                    });

                Assert(objectBaseIt != classDefinitions.End(), "ObjectBase class definition not found among builtins");

                // init ids and add dependency modules
                for (const UniquePtr<Module>& mod : m_analyzer.GetModules())
                {
                    Set<Module*> dependencyModules;

                    Proc<void(const ClassDefinition& srcClassDef, const ASTType* type)> AddDependenciesRecur;
                    AddDependenciesRecur = [&](const ClassDefinition& srcClassDef, const ASTType* type)
                    {
                        if (!type)
                        {
                            return;
                        }

                        if (type->isPointer)
                        {
                            AddDependenciesRecur(srcClassDef, type->ptrTo.Get());
                            return;
                        }

                        if (type->isLvalueReference || type->isRvalueReference)
                        {
                            AddDependenciesRecur(srcClassDef, type->refTo.Get());
                            return;
                        }

                        if (type->isArray)
                        {
                            AddDependenciesRecur(srcClassDef, type->arrayOf.Get());
                            return;
                        }

                        if (type->isTemplate)
                        {
                            for (const Handle<AstTemplateArgument>& templateArgument : type->templateArguments)
                            {
                                Assert(templateArgument != nullptr);

                                if (templateArgument->type != nullptr)
                                {
                                    AddDependenciesRecur(srcClassDef, templateArgument->type.Get());
                                }
                            }

                            return;
                        }

                        if (type->isFunction)
                        {
                            const ASTFunctionType* functionType = dynamic_cast<const ASTFunctionType*>(type);
                            Assert(functionType != nullptr);

                            AddDependenciesRecur(srcClassDef, functionType->returnType.Get());

                            for (const Handle<AstMemberDecl>& param : functionType->parameters)
                            {
                                AddDependenciesRecur(srcClassDef, param->type.Get());
                            }

                            return;
                        }

                        if (type->typeName.HasValue())
                        {
                            const ClassDefinition* depClass = m_analyzer.FindClassDefinition(type->typeName->ToString(/* includeNamespace */ false));

                            if (depClass != nullptr && depClass->declModule != nullptr && depClass->declModule != mod.Get())
                            {
                                dependencyModules.Insert(depClass->declModule);
                            }
                        }
                    };

                    for (auto& it : mod->GetClasses())
                    {
                        for (MemberDef& definition : it.second.members)
                        {
                            AddDependenciesRecur(it.second, definition.cxxType.Get());
                        }

                        if (classDefinitionIds.Contains(it.second.name))
                        {
                            m_analyzer.AddError(HYP_MAKE_ERROR(AnalyzerError, "Duplicate ClassDefinition name found: {}", mod->GetPath(), 0, it.second.name));

                            continue;
                        }

                        Assert(it.second.staticIndex == -1);
                        Assert(it.second.numDescendants == 0);

                        const uint32 classDefinitionId = uint32(classDefinitions.Size());

                        classDefinitionIds[it.second.name] = classDefinitionId;

                        classDefinitions.PushBack(&it.second);
                    }

                    if (dependencyModules.Any())
                    {
                        for (Module* dependencyModule : dependencyModules)
                        {
                            mod->AddDependencyModule(dependencyModule);
                        }
                    }
                }

                Array<Array<uint32>, DynamicAllocator> derived;
                derived.Resize(classDefinitions.Size());

                for (const ClassDefinition* classDefinition : classDefinitions)
                {
                    const uint32 child = classDefinitionIds.At(classDefinition->name);

                    for (const String& baseClassName : classDefinition->baseClassNames)
                    {
                        const auto parentIt = classDefinitionIds.Find(baseClassName);

                        if (parentIt == classDefinitionIds.End())
                        {
                            continue;
                        }

                        const uint32 parent = parentIt->second;
                        Assert(parent < classDefinitions.Size());

                        derived[parent].PushBack(child);
                    }
                }

                Array<uint32> indeg;
                indeg.Resize(classDefinitions.Size());

                for (const Array<uint32>& children : derived)
                {
                    for (uint32 child : children)
                    {
                        indeg[child]++;
                    }
                }

                Array<uint32> roots;

                for (size_t i = 0; i < indeg.Size(); i++)
                {
                    if (indeg[i] == 0)
                    {
                        roots.PushBack(i);
                    }
                }

                Array<uint32> stack;
                stack.Reserve(classDefinitions.Size());

                uint32 nextOut = 1; // 0 is reserved for ObjectBase

                Proc<void(uint32)> TopologicalSort;
                TopologicalSort = [&](uint32 id)
                {
                    Assert(id < classDefinitions.Size());

                    ClassDefinition* classDefinition = classDefinitions[id];

                    // skip assignment for builtin ObjectBase type (0)
                    const bool isBaseClass = classDefinition->name == "ObjectBase";

                    if (!isBaseClass)
                    {
                        classDefinition->staticIndex = int(nextOut++);
                    }

                    const uint32 start = uint32(classDefinition->staticIndex);

                    stack.PushBack(id);

                    for (uint32 i : derived[id])
                    {
                        if (classDefinitions[i]->staticIndex == -1)
                        {
                            TopologicalSort(i);
                        }
                    }

                    stack.PopBack();

                    classDefinition->numDescendants = nextOut - start - 1;
                };

                for (uint32 root : roots)
                {
                    TopologicalSort(root);
                }
            }, m_threadPool);
    }

    Task<void> GenerateOutputFiles()
    {
        Assert(m_analyzer.GetCXXOutputDirectory().MkDir(), "Failed to create C++ output directory: {}", m_analyzer.GetCXXOutputDirectory());

        Task<void> task;

        TaskBatch* batch = new TaskBatch();
        batch->pool = &m_threadPool;
        batch->OnComplete
            .Bind([batch, promise = task.Promise()]()
                {
                    promise->Fulfill();

                    DeferDeleteTaskBatch(batch);
                })
            .Detach();

        SharedPtr<Module> builtinsModule = MakeShared<Module>(FilePath());

        // add all builtins to a fake module for generation
        for (auto& it : m_analyzer.GetBuiltinClasses())
        {
            builtinsModule->GetClasses().Set(it.second.name, it.second);
        }

        if (m_analyzer.GetCSharpOutputDirectory().Any())
        {
            Assert(m_analyzer.GetCSharpOutputDirectory().MkDir(), "Failed to create C# output directory: {}", m_analyzer.GetCSharpOutputDirectory());

            static CSharpModuleGenerator s_csharpModuleGenerator;

            if (builtinsModule->GetClasses().Any())
            {
                // generate builtins first
                batch->AddTask([this, builtinsModule]()
                    {
                        if (Result res = s_csharpModuleGenerator.Generate(m_analyzer, *builtinsModule); res.HasError())
                        {
                            m_analyzer.AddError(AnalyzerError(res.GetError(), FilePath("<builtins>")));
                        }
                    });
            }

            for (const UniquePtr<Module>& mod : m_analyzer.GetModules())
            {
                if (mod->GetClasses().Empty())
                {
                    continue;
                }

                // csharp modules can be processed async from C++ modules
                batch->AddTask([this, &mod = *mod]()
                    {
                        if (Result res = s_csharpModuleGenerator.Generate(m_analyzer, mod); res.HasError())
                        {
                            m_analyzer.AddError(AnalyzerError(res.GetError(), mod.GetPath()));
                        }
                    });
            }
        }

        if (m_analyzer.GetHypScriptOutputDirectory().Any())
        {
            Assert(m_analyzer.GetHypScriptOutputDirectory().MkDir(), "Failed to create HypScript output directory: {}", m_analyzer.GetHypScriptOutputDirectory());

            HypScriptModuleGenerator hypscriptModuleGenerator;

            // for hypscript, we want to generate all modules and then merge them into one file
            // but we need to sort modules topologically to ensure dependencies come first

            FileByteWriter hypscriptModuleWriter(m_analyzer.GetHypScriptOutputDirectory() / "Lib.hyp");

            if (!hypscriptModuleWriter.IsOpen())
            {
                m_analyzer.AddError(HYP_MAKE_ERROR(AnalyzerError, "Failed to open HypScript output file: {}", {}, -1, m_analyzer.GetHypScriptOutputDirectory() / "Lib.hyp"));
            }

            hypscriptModuleWriter.WriteString(*s_hypscriptPreamble);

            if (builtinsModule->GetClasses().Any())
            {
                // generate builtins first
                if (Result res = hypscriptModuleGenerator.Generate(m_analyzer, *builtinsModule, hypscriptModuleWriter); res.HasError())
                {
                    m_analyzer.AddError(AnalyzerError(res.GetError(), FilePath("<builtins>")));
                }
            }

            Array<Module*> sortedModules = SortModulesTopologically();

            for (Module* mod : sortedModules)
            {
                if (mod->GetClasses().Empty())
                {
                    continue;
                }

                MemoryByteWriter<DynamicAllocator> writer;

                if (Result res = hypscriptModuleGenerator.Generate(m_analyzer, *mod, writer); res.HasError())
                {
                    m_analyzer.AddError(AnalyzerError(res.GetError(), mod->GetPath()));

                    continue;
                }

                if (writer.Position() == 0) // nothing was written
                {
                    continue;
                }

                hypscriptModuleWriter.Write(writer.GetBuffer());
            }

            hypscriptModuleWriter.Close();
        }

        CXXModuleGenerator cxxModuleGenerator;

        // Generate the ClassDecl header (shared by both modes)
        {
            FilePath classDeclHeaderPath = m_analyzer.GetCXXOutputDirectory() / "ClassDecls.inc";
            FileByteWriter classDeclWriter(classDeclHeaderPath);

            if (!classDeclWriter.IsOpen())
            {
                m_analyzer.AddError(HYP_MAKE_ERROR(AnalyzerError, "Failed to open ClassDecl header file: {}", {}, -1, classDeclHeaderPath));
            }
            else
            {
                if (Result res = cxxModuleGenerator.GenerateClassDeclHeader(m_analyzer, classDeclWriter); res.HasError())
                {
                    m_analyzer.AddError(AnalyzerError(res.GetError(), classDeclHeaderPath));
                }

                classDeclWriter.Close();
            }
        }

        // Determine all unique API macros used across modules (always include ENGINE_API for builtins/fallback)
        Set<String> apiMacros;
        apiMacros.Insert("ENGINE_API");

        for (const UniquePtr<Module>& mod : m_analyzer.GetModules())
        {
            if (!mod->GetClasses().Empty())
            {
                apiMacros.Insert(CXXModuleGenerator::GetAPIMacroForModule(m_analyzer, *mod));
            }
        }

        // Generate a separate ClassDecls implementation file per API macro group
        for (const String& apiMacro : apiMacros)
        {
            const String outputSubdir = CXXModuleGenerator::GetClassDeclsOutputSubdirForAPIMacro(apiMacro);

            FilePath classDeclImplDir = m_analyzer.GetCXXOutputDirectory();

            if (outputSubdir.Any())
            {
                classDeclImplDir = classDeclImplDir / outputSubdir;
                Assert(classDeclImplDir.MkDir(), "Failed to create ClassDecl output subdirectory: {}", classDeclImplDir);
            }

            const FilePath classDeclImplPath = classDeclImplDir / "ClassDecls.cpp";
            FilePath tmpClassDeclImplPath = classDeclImplPath + ".tmp";
            FileByteWriter classDeclImplWriter(tmpClassDeclImplPath);

            if (!classDeclImplWriter.IsOpen())
            {
                m_analyzer.AddError(HYP_MAKE_ERROR(AnalyzerError, "Failed to open ClassDecl implementation file: {}", {}, -1, tmpClassDeclImplPath));
            }
            else
            {
                if (Result res = cxxModuleGenerator.GenerateClassDeclImplementation(m_analyzer, apiMacro, classDeclImplWriter); res.HasError())
                {
                    m_analyzer.AddError(AnalyzerError(res.GetError(), tmpClassDeclImplPath));
                }

                classDeclImplWriter.Close();
            }

            ReplaceFileIfDifferent(tmpClassDeclImplPath, classDeclImplPath);
        }

        if (m_cxxMode == CXXGenerationMode::INL)
        {
            // Pre-scan for duplicate flattened .inl filenames (e.g., Foo.generated.inl)
            Map<String, FilePath> seenInlNames; // maps inl filename to first header path encountered
            Set<String> duplicateInlNames;      // set of filenames that collide

            for (const UniquePtr<Module>& mod : m_analyzer.GetModules())
            {
                if (mod->GetClasses().Empty())
                {
                    continue;
                }

                const FilePath& headerPath = mod->GetPath();
                if (!headerPath.Any())
                {
                    continue;
                }

                const String stem = StringUtil::StripExtension(headerPath.Basename());
                const String inlFilename = stem + ".generated.inl";

                if (seenInlNames.Contains(inlFilename))
                {
                    const FilePath& firstHeaderPath = seenInlNames.At(inlFilename);

                    if (!duplicateInlNames.Contains(inlFilename))
                    {
                        duplicateInlNames.Insert(inlFilename);
                        HYP_LOG(Tool, Error, "Duplicate inline output filename '{}' would be generated from:\n - {}\n - {}", inlFilename, firstHeaderPath, headerPath);

                        m_analyzer.AddError(HYP_MAKE_ERROR(AnalyzerError, "Duplicate inline output filename detected in flattened inline mode: {} vs {}", inlFilename, {}, -1, firstHeaderPath, headerPath));
                    }
                    else
                    {
                        // Additional duplicate beyond the first two
                        HYP_LOG(Tool, Error, "Duplicate inline output filename '{}' also produced by: {} (first seen at {})", inlFilename, headerPath, firstHeaderPath);
                        m_analyzer.AddError(HYP_MAKE_ERROR(AnalyzerError, "Duplicate inline output filename detected in flattened inline mode", {}, -1, headerPath));
                    }
                }
                else
                {
                    seenInlNames[inlFilename] = headerPath;
                }
            }

            // Inline mode: generate one small cpp for builtins and per-module .inl files
            if (builtinsModule->GetClasses().Any())
            {
                const FilePath builtinsDir = m_analyzer.GetCXXOutputDirectory() / "Core";
                Assert(builtinsDir.MkDir(), "Failed to create builtins output directory: {}", builtinsDir);
                const FilePath builtinsPath = builtinsDir / "Builtins.cpp";
                FileByteWriter builtinsWriter { builtinsPath };

                if (!builtinsWriter.IsOpen())
                {
                    m_analyzer.AddError(HYP_MAKE_ERROR(AnalyzerError, "Failed to open builtins output file: {}", {}, -1, builtinsPath));
                }
                else
                {
                    builtinsWriter.WriteString(GetGeneratedFilePreamble(String::empty));
                    builtinsWriter.WriteString("#include <Core/Reflection/ClassUtils.hpp>\n");
                    if (Result res = cxxModuleGenerator.Generate(m_analyzer, *builtinsModule, builtinsWriter); res.HasError())
                    {
                        m_analyzer.AddError(AnalyzerError(res.GetError(), FilePath("<builtins>")));
                    }
                    builtinsWriter.Close();
                }
            }

            for (const UniquePtr<Module>& mod : m_analyzer.GetModules())
            {
                if (mod->GetClasses().Empty())
                {
                    continue;
                }

                // Skip modules that would generate a duplicate flattened inline filename
                {
                    const FilePath& headerPath = mod->GetPath();
                    if (headerPath.Any())
                    {
                        const String stem = StringUtil::StripExtension(headerPath.Basename());
                        const String inlFilename = stem + ".generated.inl";
                        if (duplicateInlNames.Contains(inlFilename))
                        {
                            // Error already recorded in the pre-scan; skip generating/including to avoid overwrite
                            continue;
                        }
                    }
                }

                const FilePath inlPath = cxxModuleGenerator.GetInlineOutputFilePath(m_analyzer, *mod);
                Assert(inlPath.BasePath().MkDir(), "Failed to create output directory for {}", inlPath);

                FilePath tmpInlPath = inlPath + ".tmp";

                FileByteWriter inlWriter { tmpInlPath };
                if (!inlWriter.IsOpen())
                {
                    m_analyzer.AddError(HYP_MAKE_ERROR(AnalyzerError, "Failed to open inline output file: {}", {}, -1, tmpInlPath));
                    continue;
                }

                // Generate inline content without includes
                if (Result res = cxxModuleGenerator.GenerateInline(m_analyzer, *mod, inlWriter); res.HasError())
                {
                    m_analyzer.AddError(AnalyzerError(res.GetError(), mod->GetPath()));
                    inlWriter.Close();
                    continue;
                }

                inlWriter.Close();

                // Inject include into the corresponding .cpp file
                Result res = InjectInlineIncludeForModule(*mod, inlPath);

                if (res.HasError())
                {
                    m_analyzer.AddError(AnalyzerError(res.GetError(), mod->GetPath()));
                    continue;
                }

                ReplaceFileIfDifferent(tmpInlPath, inlPath);
            }

            TaskSystem::GetInstance().EnqueueBatch(batch);

            return task;
        }

        static constexpr uint32 IdealCxxModuleFileSize = JumboBuildEnabled ? JumboBuildIdealFileSize : 1;

        uint32 fileIndex = 0;
        char filenameBuffer[256] = {};

        FileByteWriter* cxxModuleWriter = nullptr;

        auto toLetters = [](uint32 idx, char* dst, size_t cap)
        {
            char buf[32];
            size_t n = 0;

            ++idx;
            while (idx)
            {
                uint32 r = (idx - 1) % 26;
                buf[n++] = char('A' + r);
                idx = (idx - 1) / 26;
            }

            if (n + 4 >= cap)
            {
                return false;
            }

            for (size_t i = 0; i < n; ++i)
            {
                dst[i] = buf[n - 1 - i];
            }

            dst[n] = '\0';

            return true;
        };

        auto updateFilenameBuffer = [&]()
        {
            Assert(toLetters(fileIndex, filenameBuffer, sizeof(filenameBuffer)));

            std::strcat(filenameBuffer, ".cpp");

            ++fileIndex;
        };

        if (builtinsModule->GetClasses().Any())
        {
            // generate builtins first
            updateFilenameBuffer();

            cxxModuleWriter = new FileByteWriter(m_analyzer.GetCXXOutputDirectory() / filenameBuffer);

            cxxModuleWriter->WriteString(GetGeneratedFilePreamble(String::empty));

            // add main required header that is shared across all generated modules.
            cxxModuleWriter->WriteString("#include <Core/Reflection/ClassUtils.hpp>\n");

            if (Result res = cxxModuleGenerator.Generate(m_analyzer, *builtinsModule, *cxxModuleWriter); res.HasError())
            {
                m_analyzer.AddError(AnalyzerError(res.GetError(), FilePath("<builtins>")));
            }
        }

        for (const UniquePtr<Module>& mod : m_analyzer.GetModules())
        {
            if (mod->GetClasses().Empty())
            {
                continue;
            }

            if (!cxxModuleWriter || cxxModuleWriter->Position() >= IdealCxxModuleFileSize)
            {
                if (cxxModuleWriter)
                {
                    cxxModuleWriter->Close();

                    delete cxxModuleWriter;
                    cxxModuleWriter = nullptr;
                }

                updateFilenameBuffer();

                cxxModuleWriter = new FileByteWriter(m_analyzer.GetCXXOutputDirectory() / filenameBuffer);

                cxxModuleWriter->WriteString(GetGeneratedFilePreamble(FilePath::Relative(mod->GetPath(), m_analyzer.GetSourceDirectory())));

                // add main required header that is shared across all generated modules.
                cxxModuleWriter->WriteString("#include <Core/Reflection/ClassUtils.hpp>\n");
            }

            if (Result res = cxxModuleGenerator.Generate(m_analyzer, *mod, *cxxModuleWriter); res.HasError())
            {
                m_analyzer.AddError(AnalyzerError(res.GetError(), mod->GetPath()));
            }
        }

        if (cxxModuleWriter != nullptr)
        {
            cxxModuleWriter->Close();

            delete cxxModuleWriter;
            cxxModuleWriter = nullptr;
        }

        // In CPP mode, ensure any previously injected inline includes are removed
        if (m_cxxMode == CXXGenerationMode::CPP)
        {
            for (const UniquePtr<Module>& mod : m_analyzer.GetModules())
            {
                if (mod->GetClasses().Empty())
                {
                    continue;
                }

                const FilePath inlPath = cxxModuleGenerator.GetInlineOutputFilePath(m_analyzer, *mod);
                if (Result res = RemoveInlineIncludeForModule(*mod, inlPath); res.HasError())
                {
                    m_analyzer.AddError(AnalyzerError(res.GetError(), mod->GetPath()));
                }
            }
        }

        TaskSystem::GetInstance().EnqueueBatch(batch);

        return task;
    }

    // Compute the exact include line used for inline includes so insertion/removal share one source of truth
    String ComputeInlineIncludeLine(const FilePath& inlPath) const
    {
        const String includeFileName = FilePath::Relative(inlPath, m_analyzer.GetCXXOutputDirectory()).Basename();
        return HYP_FORMAT("#include <{}>",includeFileName);
    }

    Result InjectInlineIncludeForModule(const Module& mod, const FilePath& inlPath)
    {
        // Compute expected source file path by replacing extension with .cpp (try variants)
        const FilePath& headerPath = mod.GetPath();
        if (!headerPath.Any())
        {
            return {}; // nothing to do
        }

        const String stem = StringUtil::StripExtension(headerPath.Basename());
        const FilePath baseDir = headerPath.BasePath();

        const FilePath cxxPath = baseDir / (stem + ".cpp");

        // Foo.generated.cpp file creation
        if (!cxxPath.Exists() || cxxPath.IsDirectory())
        {
            // No implementation file exists in src; create a small generated .cpp that includes the header and the .inl
            const FilePath relHeaderPath = FilePath::Relative(headerPath, m_analyzer.GetSourceDirectory());

            const FilePath genCxxPath = inlPath.BasePath() / (stem + ".generated.cpp");
            FilePath tmpGenCxxPath = genCxxPath + ".tmp";

            Assert(genCxxPath.BasePath().MkDir(), "Failed to create output directory for {}", genCxxPath);

            // Compute include path for .inl relative to generated dir
            const FilePath relInlPathForGen = FilePath::Relative(inlPath, m_analyzer.GetCXXOutputDirectory());

            FileByteWriter writer { tmpGenCxxPath };
            if (!writer.IsOpen())
            {
                return HYP_MAKE_ERROR(Error, "Failed to open generated implementation file '{}' for writing", tmpGenCxxPath);
            }

            writer.WriteString(GetGeneratedFilePreamble(FilePath::Relative(headerPath, m_analyzer.GetSourceDirectory())));
            writer.WriteString(HYP_FORMAT("#include <{}>\n", relHeaderPath.ReplaceAll("\\", "/")));

            // Include dependency module headers (relative to source directory), like the non-inline path
            if (mod.GetDependencyModules().Any())
            {
                for (Module* dependencyModule : mod.GetDependencyModules())
                {
                    Assert(dependencyModule != nullptr);

                    if (!dependencyModule->GetPath().Any())
                    {
                        HYP_LOG(Tool, Error, "Dependency module has no path! Skipping include.");
                        continue;
                    }

                    FilePath relDepPath = FilePath::Relative(dependencyModule->GetPath(), m_analyzer.GetSourceDirectory());
                    String includeDepPathStr = relDepPath.Data();
                    writer.WriteString(HYP_FORMAT("#include <{}>\n", includeDepPathStr.ReplaceAll("\\", "/")));
                }

                writer.WriteString("\n");
            }

            writer.WriteString(HYP_FORMAT("#include <{}>\n", relInlPathForGen.Basename()));
            writer.Close();

            return ReplaceFileIfDifferent(tmpGenCxxPath, genCxxPath);
        }

        // Compute include path relative to generated include root (single source of truth)
        const String includeLine = ComputeInlineIncludeLine(inlPath);

        Array<String> lines;

        {
            FileBufferedReaderSource readerSource { cxxPath };

            if (!readerSource.IsOK())
            {
                return HYP_MAKE_ERROR(Error, "Failed to open source file '{}' for reading during inline include injection", cxxPath);
            }

            BufferedByteReader reader { &readerSource };

            lines = reader.ReadAllLines();

            for (const String& line : lines)
            {
                if (line.Contains(includeLine))
                {
                    // Already included; don't write to file to avoid forcing unnecessary recompile
                    return {};
                }
            }

            reader.Close();
        }

        // To determine insertion point,
        // - Prefer after the last #include at preprocessor depth 0
        // - Otherwise, before the first 'namespace' encountered at depth 0
        // - Never insert while within a preprocessor conditional block

        auto isPPIf = [](const String& s)
        {
            return s.StartsWith("#if") || s.StartsWith("#ifdef") || s.StartsWith("#ifndef");
        };

        auto isPPEndif = [](const String& s)
        {
            return s.StartsWith("#endif");
        };

        auto isPPElseElif = [](const String& s)
        {
            return s.StartsWith("#else") || s.StartsWith("#elif");
        };

        // Scan to find insertion point:
        // - Track preprocessor depth and brace depth
        // - Remember the last top-level (#if depth==0, braceDepth==0) include line
        // - Remember the first top-level brace line, namespace line, and non-PP code line

        // da rules:
        //   If a last top-level include exists: insert before the earliest of
        //   (first top-level brace/namespace/other code) that occurs AFTER that include.
        //   Otherwise: insert before the first top-level brace, else namespace, else first code; fallback to end.

        size_t lastTopInclude = size_t(-1);
        size_t firstTopNamespace = size_t(-1);
        size_t firstTopBraceLine = size_t(-1);
        size_t firstTopNonPPCode = size_t(-1);

        int preprocessorDepth = 0;
        int braceDepth = 0;
        bool inBlockComment = false;

        for (size_t i = 0; i < lines.Size(); ++i)
        {
            const String& raw = lines[i];
            const String line = raw.Trimmed();

            // Update preprocessor depth at start of line
            if (line[0] == '#')
            {
                if (isPPIf(line))
                {
                    ++preprocessorDepth;
                }
                else if (isPPEndif(line))
                {
                    if (preprocessorDepth > 0)
                    {
                        --preprocessorDepth;
                    }
                }
                else if (isPPElseElif(line))
                {
                    // depth unchanged
                }
            }

            // Record last top-level include
            if (preprocessorDepth == 0 && braceDepth == 0 && line.StartsWith("#include"))
            {
                lastTopInclude = i;
            }

            if (preprocessorDepth == 0)
            {
                // Walk characters to (a) update braceDepth while ignoring comments, and
                // (b) detect whether this line has any non-comment, non-PP code at top level.
                bool lineHasCode = false;
                bool inLineComment = false;

                for (size_t k = 0; k < raw.Size(); ++k)
                {
                    const char c = raw[k];

                    // Handle line comment start
                    if (!inBlockComment && !inLineComment && k + 1 < raw.Size() && raw[k] == '/' && raw[k + 1] == '/')
                    {
                        inLineComment = true;

                        break; // rest of line is comment
                    }

                    // Handle block comment transitions
                    if (!inLineComment && k + 1 < raw.Size())
                    {
                        if (!inBlockComment && raw[k] == '/' && raw[k + 1] == '*')
                        {
                            inBlockComment = true;
                            ++k; // skip '*'

                            continue;
                        }
                        else if (inBlockComment && raw[k] == '*' && raw[k + 1] == '/')
                        {
                            inBlockComment = false;
                            ++k; // skip '/'

                            continue;
                        }
                    }

                    if (inBlockComment || inLineComment)
                    {
                        continue;
                    }

                    // Detect first top-level namespace token
                    if (braceDepth == 0 && firstTopNamespace == size_t(-1))
                    {
                        // Cheap check: use trimmed line to determine namespace start
                        if (line.StartsWith("namespace"))
                        {
                            firstTopNamespace = i;
                        }
                    }

                    // Update brace depth, recording first top-level '{' location
                    if (raw[k] == '{')
                    {
                        if (braceDepth == 0 && firstTopBraceLine == size_t(-1))
                        {
                            firstTopBraceLine = i;
                        }

                        ++braceDepth;

                        continue;
                    }
                    if (raw[k] == '}')
                    {
                        if (braceDepth > 0)
                        {
                            --braceDepth;
                        }

                        continue;
                    }

                    // Non-PP, non-comment, non-whitespace code at top-level
                    if (braceDepth == 0 && firstTopNonPPCode == size_t(-1) && c != ' ' && c != '\t' && line[0] != '#')
                    {
                        lineHasCode = true;
                        // don't break; continue scanning to keep braceDepth correct
                    }
                }

                if (braceDepth == 0 && firstTopNonPPCode == size_t(-1) && lineHasCode)
                {
                    firstTopNonPPCode = i;
                }
            }
            else
            {
                // Even inside PP blocks, keep braceDepth roughly in sync to avoid drift
                bool inLineComment = false;

                for (size_t k = 0; k < raw.Size(); ++k)
                {
                    // basic comment skipping
                    if (!inBlockComment && !inLineComment && k + 1 < raw.Size() && raw[k] == '/' && raw[k + 1] == '/')
                    {
                        inLineComment = true;
                        break;
                    }
                    if (!inLineComment && k + 1 < raw.Size())
                    {
                        if (!inBlockComment && raw[k] == '/' && raw[k + 1] == '*')
                        {
                            inBlockComment = true;
                            ++k;
                            continue;
                        }
                        if (inBlockComment && raw[k] == '*' && raw[k + 1] == '/')
                        {
                            inBlockComment = false;
                            ++k;
                            continue;
                        }
                    }

                    if (inBlockComment || inLineComment)
                    {
                        continue;
                    }

                    if (raw[k] == '{')
                    {
                        ++braceDepth;
                    }
                    else if (raw[k] == '}')
                    {
                        if (braceDepth > 0)
                        {
                            --braceDepth;
                        }
                    }
                }
            }
        }

        // Only insert if we have at least one top-level include; otherwise, do not inject into the source file.
        if (lastTopInclude == size_t(-1))
        {
            return {}; // respect "after last include" rule; do nothing if no includes
        }

        size_t insertIndex = size_t(-1);

        if (lastTopInclude != size_t(-1))
        {
            auto checkGuardIndex = [lastTopInclude](size_t idx, size_t& outIdx) -> bool
            {
                if (idx != size_t(-1) && idx > lastTopInclude)
                {
                    if (outIdx == size_t(-1) || idx < outIdx)
                    {
                        outIdx = idx;

                        return true;
                    }
                }

                return false;
            };

            // Choose the earliest top-level construct AFTER the last include
            size_t guardIndex = size_t(-1);

            (void)(checkGuardIndex(firstTopBraceLine, guardIndex)
                || checkGuardIndex(firstTopNamespace, guardIndex)
                || checkGuardIndex(firstTopNonPPCode, guardIndex));

            insertIndex = (guardIndex != size_t(-1)) ? guardIndex : (lastTopInclude + 1);
        }
        else if (firstTopBraceLine != size_t(-1))
        {
            insertIndex = firstTopBraceLine; // before first top-level brace
        }
        else if (firstTopNamespace != size_t(-1))
        {
            insertIndex = firstTopNamespace; // before first top-level namespace
        }
        else if (firstTopNonPPCode != size_t(-1))
        {
            insertIndex = firstTopNonPPCode; // before first top-level code
        }
        else
        {
            // Fallback: append at end
            insertIndex = lines.Size();
        }

        // Normalize spacing: exactly one blank line above and below the inserted include line.
        // First, ensure the insertIndex is within [0, lines.Size()].
        if (insertIndex == size_t(-1))
        {
            insertIndex = 0;
        }

        if (insertIndex > lines.Size())
        {
            insertIndex = lines.Size();
        }

        // Collapse/ensure one blank line above
        size_t aboveCount = 0;
        for (size_t i = insertIndex; i > 0;)
        {
            const size_t j = i - 1;

            if (lines[j].Trimmed().Empty())
            {
                ++aboveCount;
                i = j;
            }
            else
            {
                break;
            }
        }
        if (aboveCount == 0)
        {
            lines.Insert(lines.Begin() + insertIndex, String::empty);
            ++insertIndex; // include goes after the blank we just inserted
        }
        else if (aboveCount > 1)
        {
            // remove extra blanks leaving exactly one
            size_t toRemove = aboveCount - 1;

            while (toRemove-- > 0)
            {
                lines.Erase(lines.Begin() + (insertIndex - 1));
                --insertIndex;
            }
        }

        // Insert the include line
        lines.Insert(lines.Begin() + insertIndex, includeLine);

        // Ensure exactly one blank line below
        size_t belowIdx = insertIndex + 1;
        size_t belowCount = 0;
        for (size_t i = belowIdx; i < lines.Size(); ++i)
        {
            if (lines[i].Trimmed().Empty())
            {
                ++belowCount;
            }
            else
            {
                break;
            }
        }
        if (belowCount == 0)
        {
            lines.Insert(lines.Begin() + (insertIndex + 1), String::empty);
        }
        else if (belowCount > 1)
        {
            // remove extras beyond one
            size_t removeFrom = insertIndex + 2; // keep the first blank directly after include
            size_t removeEnd = removeFrom + (belowCount - 1);

            if (removeEnd > lines.Size())
            {
                removeEnd = lines.Size();
            }

            while (removeFrom < removeEnd)
            {
                lines.Erase(lines.Begin() + removeFrom);
                --removeEnd;
            }
        }

        // Write to temp file and replace if different
        FilePath tmpCxxPath = cxxPath + ".tmp";
        FileByteWriter writer { tmpCxxPath };
        if (!writer.IsOpen())
        {
            return HYP_MAKE_ERROR(Error, "Failed to open source file '{}' for writing during inline include injection", tmpCxxPath);
        }

        const String joined = String::Join(lines, '\n') + '\n';
        writer.WriteString(joined);
        writer.Close();

        return ReplaceFileIfDifferent(tmpCxxPath, cxxPath);
    }

    // In CPP mode, remove the previously injected inline include line (exact match) and clean up nearby blank lines
    Result RemoveInlineIncludeForModule(const Module& mod, const FilePath& inlPath)
    {
        const FilePath& headerPath = mod.GetPath();
        if (!headerPath.Any())
        {
            return {}; // nothing to do
        }

        const String stem = StringUtil::StripExtension(headerPath.Basename());
        const FilePath baseDir = headerPath.BasePath();

        const FilePath cxxPath = baseDir / (stem + ".cpp");
        const FilePath genCxxPath = inlPath.BasePath() / (stem + ".generated.cpp");

        const String includeLine = ComputeInlineIncludeLine(inlPath);

        auto removeFromFile = [&](const FilePath& path) -> Result
        {
            if (!path.Exists() || path.IsDirectory())
            {
                return {};
            }

            FileBufferedReaderSource source { path };
            if (!source.IsOK())
            {
                return HYP_MAKE_ERROR(Error, "Failed to open source file '{}' for reading during inline include removal", path);
            }

            BufferedByteReader reader { &source };

            Array<String> lines = reader.ReadAllLines();
            const String oldText = String::Join(lines, '\n') + '\n';

            // Remove ALL exact matches of the include line to be safe, cleaning surrounding blank lines
            for (;;)
            {
                // Find next include match (exact line)
                size_t matchIndex = size_t(-1);
                for (size_t i = 0; i < lines.Size(); ++i)
                {
                    if (lines[i] == includeLine)
                    {
                        matchIndex = i;
                        break;
                    }
                }

                if (matchIndex == size_t(-1))
                {
                    break; // nothing more to remove
                }

                // Before removing just the include line, check whether it's the only content in a simple
                // preprocessor block like:
                //   #ifndef HYP_TOOL
                //                   //   #endif
                // If so, remove the entire block.

                // Build stack of #if.../#endif pairs for this snapshot of lines
                Array<Pair<size_t, size_t>> ifPairs; // (ifIndex, endifIndex)
                Array<size_t> ifStack;

                auto isPPIf = [](const String& s)
                {
                    return s.StartsWith("#if") || s.StartsWith("#ifdef") || s.StartsWith("#ifndef");
                };
                auto isPPEndif = [](const String& s)
                {
                    return s.StartsWith("#endif");
                };
                auto isPPElseElif = [](const String& s)
                {
                    return s.StartsWith("#else") || s.StartsWith("#elif");
                };

                for (size_t i = 0; i < lines.Size(); ++i)
                {
                    const String t = lines[i].Trimmed();
                    if (isPPIf(t))
                    {
                        ifStack.PushBack(i);
                    }
                    else if (isPPEndif(t))
                    {
                        if (!ifStack.Empty())
                        {
                            const size_t ifIdx = ifStack.PopBack();
                            ifPairs.PushBack({ ifIdx, i });
                        }
                    }
                }

                // Select innermost enclosing pair (if any)
                size_t selIfStart = size_t(-1);
                size_t selIfEnd = size_t(-1);
                for (const auto& pr : ifPairs)
                {
                    if (pr.first < matchIndex && matchIndex < pr.second)
                    {
                        if (selIfStart == size_t(-1) || pr.first > selIfStart)
                        {
                            selIfStart = pr.first;
                            selIfEnd = pr.second;
                        }
                    }
                }

                auto collapseBoundaryToSingleBlank = [&](size_t boundaryIndex)
                {
                    // After a removal, maintain at most one blank line between the previous and next non-empty lines,
                    // and ensure at least one blank if both sides are non-empty.
                    if (lines.Empty())
                        return;

                    const size_t prevIdx = boundaryIndex > 0 ? boundaryIndex - 1 : size_t(-1);
                    const size_t nextIdx = boundaryIndex < lines.Size() ? boundaryIndex : size_t(-1);

                    const bool prevExists = prevIdx != size_t(-1);
                    const bool nextExists = nextIdx != size_t(-1);

                    const bool prevNonEmpty = prevExists && !lines[prevIdx].Trimmed().Empty();
                    const bool nextNonEmpty = nextExists && !lines[nextIdx].Trimmed().Empty();

                    // Compress multiple blank lines above to at most one
                    if (prevExists && lines[prevIdx].Trimmed().Empty())
                    {
                        size_t scan = prevIdx;
                        while (scan > 0 && lines[scan - 1].Trimmed().Empty())
                        {
                            lines.Erase(lines.Begin() + (scan - 1));
                            --scan;
                            --boundaryIndex;
                        }
                    }

                    // Recompute indices if array changed size
                    const size_t pIdx = boundaryIndex > 0 ? boundaryIndex - 1 : size_t(-1);
                    size_t nIdx = boundaryIndex < lines.Size() ? boundaryIndex : size_t(-1);

                    bool blankAbove = pIdx != size_t(-1) && lines[pIdx].Trimmed().Empty();
                    bool blankBelow = nIdx != size_t(-1) && lines[nIdx].Trimmed().Empty();

                    // If both sides have a blank, drop one (prefer dropping below)
                    if (blankAbove && blankBelow)
                    {
                        lines.Erase(lines.Begin() + nIdx);
                        blankBelow = false;
                    }

                    // If there are multiple blank lines below, collapse to one
                    if (blankBelow)
                    {
                        while ((nIdx + 1) < lines.Size() && lines[nIdx + 1].Trimmed().Empty())
                        {
                            lines.Erase(lines.Begin() + (nIdx + 1));
                        }
                    }

                    // Ensure at least one blank line if both neighbors are non-empty and no blank exists
                    const bool pNonEmpty = (pIdx != size_t(-1)) && !lines[pIdx].Trimmed().Empty();
                    const bool nNonEmpty = (nIdx != size_t(-1)) && !lines[nIdx].Trimmed().Empty();
                    if (pNonEmpty && nNonEmpty && !blankAbove && !blankBelow)
                    {
                        lines.Insert(lines.Begin() + nIdx, String::empty);
                    }
                };

                bool removedBlock = false;
                if (selIfStart != size_t(-1))
                {
                    // Verify there are no #else/#elif in the block and the include is the only non-empty content
                    bool anyElseOrElif = false;
                    bool onlyInclude = true;
                    for (size_t i = selIfStart + 1; i < selIfEnd; ++i)
                    {
                        const String t = lines[i].Trimmed();
                        if (isPPElseElif(t))
                        {
                            anyElseOrElif = true;
                            break;
                        }
                        if (i == matchIndex)
                        {
                            continue;
                        }
                        if (t.Any())
                        {
                            onlyInclude = false;
                            break;
                        }
                    }

                    if (!anyElseOrElif && onlyInclude)
                    {
                        // Remove entire block [selIfStart, selIfEnd]
                        const size_t removeCount = selIfEnd - selIfStart + 1;
                        for (size_t c = 0; c < removeCount && selIfStart < lines.Size(); ++c)
                        {
                            lines.Erase(lines.Begin() + selIfStart);
                        }

                        // Normalize spacing at boundary where the block was
                        collapseBoundaryToSingleBlank(selIfStart);
                        removedBlock = true;
                    }
                }

                if (!removedBlock)
                {
                    // Remove just the include line
                    lines.Erase(lines.Begin() + matchIndex);
                    // Normalize spacing at the removal point
                    collapseBoundaryToSingleBlank(matchIndex);
                }
            }

            const String newText = String::Join(lines, '\n') + '\n';

            if (newText == oldText)
            {
                return {}; // nothing changed
            }

            FileByteWriter writer { path };
            if (!writer.IsOpen())
            {
                return HYP_MAKE_ERROR(Error, "Failed to open source file '{}' for writing during inline include removal", path);
            }

            writer.WriteString(newText);
            writer.Close();

            return {};
        };

        // Prefer removing from the real source .cpp; if it doesn't exist, try the generated .cpp (created in INL mode)
        if (Result res = removeFromFile(cxxPath); res.HasError())
        {
            return res;
        }

        if (Result res = removeFromFile(genCxxPath); res.HasError())
        {
            return res;
        }

        return {};
    }

    Array<Module*> SortModulesTopologically()
    {
        // Build a map from class names to modules that contain them
        Map<String, Module*> classToModule;
        Map<Module*, uint32> moduleToIndex;
        Array<Module*> moduleArray;

        for (const UniquePtr<Module>& mod : m_analyzer.GetModules())
        {
            if (mod->GetClasses().Empty())
            {
                continue;
            }

            const uint32 moduleIndex = uint32(moduleArray.Size());
            moduleToIndex[mod.Get()] = moduleIndex;
            moduleArray.PushBack(mod.Get());

            for (const auto& classEntry : mod->GetClasses())
            {
                classToModule[classEntry.second.name] = mod.Get();
            }
        }

        // Build dependency graph between modules
        const size_t numModules = moduleArray.Size();
        Array<Array<uint32>> dependents(numModules); // dependents[i] contains modules that depend on module i
        Array<uint32> inDegree;                      // number of modules that this module depends on
        inDegree.Resize(numModules);

        // Initialize inDegree to 0
        for (size_t i = 0; i < numModules; i++)
        {
            inDegree[i] = 0;
        }

        for (size_t i = 0; i < numModules; i++)
        {
            Module* currentModule = moduleArray[i];

            // Collect all base classes used by this module
            Set<Module*> dependencyModules;

            for (const auto& classEntry : currentModule->GetClasses())
            {
                const ClassDefinition& classDef = classEntry.second;

                for (const String& baseClassName : classDef.baseClassNames)
                {
                    auto it = classToModule.Find(baseClassName);
                    if (it != classToModule.End() && it->second != currentModule)
                    {
                        dependencyModules.Insert(it->second);
                    }
                }
            }

            // Update dependency graph: currentModule depends on dependencyModules
            // So dependencyModule should come before currentModule
            for (Module* depModule : dependencyModules)
            {
                const uint32 depModuleIndex = moduleToIndex.At(depModule);
                dependents[depModuleIndex].PushBack(i); // depModule has currentModule as dependent
                inDegree[i]++;                          // currentModule has one more dependency
            }
        }

        Array<uint32> result;
        Array<uint32> queue;

        // Find all modules with no dependencies
        for (size_t i = 0; i < numModules; i++)
        {
            if (inDegree[i] == 0)
            {
                queue.PushBack(i);
            }
        }

        while (!queue.Empty())
        {
            const uint32 currentIndex = queue.PopBack();
            result.PushBack(currentIndex);

            // Remove this module from dependency graph and check its dependents
            for (uint32 dependentIndex : dependents[currentIndex])
            {
                inDegree[dependentIndex]--;
                if (inDegree[dependentIndex] == 0)
                {
                    queue.PushBack(dependentIndex);
                }
            }
        }

        // Check for cycles
        if (result.Size() != numModules)
        {
            HYP_LOG(Tool, Warning, "Circular dependency detected in modules! Some modules may be in incorrect order.");

            // Add remaining modules to avoid missing any
            for (size_t i = 0; i < numModules; i++)
            {
                if (inDegree[i] > 0)
                {
                    result.PushBack(i);
                }
            }
        }

        // Convert indices back to module pointers
        Array<Module*> sortedModules;
        sortedModules.Reserve(result.Size());

        for (uint32 index : result)
        {
            sortedModules.PushBack(moduleArray[index]);
        }

        return sortedModules;
    }

    void LogGeneratedClasses() const
    {
        for (const UniquePtr<Module>& mod : m_analyzer.GetModules())
        {
            for (const Pair<String, ClassDefinition>& cls : mod->GetClasses())
            {
                HYP_LOG(Tool, Info, "Class: {} -> {}", cls.first, cls.second.staticIndex);

                // Log out all members
                for (const MemberDef& memberDef : cls.second.members)
                {
                    if (!memberDef.cxxType)
                    {
                        continue;
                    }

                    JSON::Value json;
                    memberDef.cxxType->ToJSON(json);

                    HYP_LOG(Tool, Info, "\tMember: {}\t{}", memberDef.name, json.ToString(true));
                }
            }
        }
    }

    void WaitWhileTaskRunning(const Task<void>& task)
    {
        AssertOnThread(g_mainThread);

        Assert(task.IsValid());

        while (!task.IsCompleted())
        {
            ThreadSleep(100);
        }
    }

    // Setup a task to delete the batch
    // Use when deleting the batch inline would cause an issue due to destructing a mutex that is currently locked.
    static void DeferDeleteTaskBatch(TaskBatch* batch)
    {
        if (!batch)
        {
            return;
        }

        TaskSystem::GetInstance().Enqueue([batch]()
            {
                delete batch;
            },
            TaskThreadPoolName::THREAD_POOL_BACKGROUND, TaskEnqueueFlags::FIRE_AND_FORGET);
    }

    WorkerThreadPool m_threadPool;
    Analyzer m_analyzer;
    CXXGenerationMode m_cxxMode = CXXGenerationMode::INL;
};

} // namespace CodeGen
} // namespace Hyperion

using namespace Hyperion;
using namespace CodeGen;

int main(int argc, char** argv)
{
    SetCurrentThreadId(g_mainThread);

    LogChannelRegistrar::GetInstance().RegisterAll();

    CommandLineArgumentDefinitions definitions;
    definitions.Add("WorkingDirectory", "", "", CommandLineArgumentFlags::REQUIRED, CommandLineArgumentType::STRING);
    definitions.Add("SourceDirectory", "", "", CommandLineArgumentFlags::REQUIRED, CommandLineArgumentType::STRING);
    definitions.Add("CXXOutputDirectory", "", "", CommandLineArgumentFlags::REQUIRED, CommandLineArgumentType::STRING);
    definitions.Add("CSharpOutputDirectory", "", "", CommandLineArgumentFlags::NONE, CommandLineArgumentType::STRING, /* defaultValue */ String::empty);
    definitions.Add("HypScriptOutputDirectory", "", "", CommandLineArgumentFlags::NONE, CommandLineArgumentType::STRING, /* defaultValue */ String::empty);
    definitions.Add("ExcludeDirectories", "", "", CommandLineArgumentFlags::NONE, CommandLineArgumentType::STRING);
    definitions.Add("ExcludeFiles", "", "", CommandLineArgumentFlags::NONE, CommandLineArgumentType::STRING);
    definitions.Add("Mode", "m", "", CommandLineArgumentFlags::NONE, Array<String> { "ParseHeaders" }, String("ParseHeaders"));
    definitions.Add("CXXMode", "", "C++ code generation mode (Cpp or Inl)", CommandLineArgumentFlags::NONE, Array<String> { "Cpp", "Inl" }, String("Inl"));

    CommandLineParser commandLineParser { &definitions };

    HYP_LOG(Tool, Info, "Starting CodeGenTool...");

    if (auto parseResult = commandLineParser.Parse(argc, argv))
    {
        // Create background thread pool
        static constexpr uint32 MaxBackgroundWorkerThreads = 1;
        TaskSystem::GetInstance().RegisterPool(TaskThreadPoolName::THREAD_POOL_BACKGROUND, MakeUnique<BackgroundWorkerPool>("BackgroundWorker", MaxBackgroundWorkerThreads));

        TaskSystem::GetInstance().Start();

        const FilePath workingDirectory = FilePath(parseResult.GetValue()["WorkingDirectory"].AsString());

        if (!workingDirectory.IsDirectory())
        {
            HYP_LOG(Tool, Error, "Working directory is not a directory: {}", workingDirectory);

            return 1;
        }

        const FilePath sourceDirectory = FilePath(parseResult.GetValue()["SourceDirectory"].AsString());

        if (!sourceDirectory.IsDirectory())
        {
            HYP_LOG(Tool, Error, "Source directory is not a directory: {}", sourceDirectory);

            return 1;
        }

        const FilePath cxxOutputDirectory = FilePath(parseResult.GetValue()["CXXOutputDirectory"].AsString());
        const FilePath csharpOutputDirectory = FilePath(parseResult.GetValue()["CSharpOutputDirectory"].AsString());
        const FilePath hypscriptOutputDirectory = FilePath(parseResult.GetValue()["HypScriptOutputDirectory"].AsString());

        Set<FilePath> excludeDirectories;
        Set<FilePath> excludeFiles;

        if (parseResult.GetValue().Contains("ExcludeDirectories"))
        {
            const JSON::JArray excludeDirectoriesJson = parseResult.GetValue()["ExcludeDirectories"].ToArray();

            for (const JSON::Value& value : excludeDirectoriesJson)
            {
                excludeDirectories.Insert(FilePath(FileSystem::RelativePath(value.ToString().Data(), sourceDirectory.Data()).c_str()));
            }
        }

        if (parseResult.GetValue().Contains("ExcludeFiles"))
        {
            const JSON::JArray excludeFilesJson = parseResult.GetValue()["ExcludeFiles"].ToArray();

            for (const JSON::Value& value : excludeFilesJson)
            {
                excludeFiles.Insert(FilePath(FileSystem::RelativePath(value.ToString().Data(), sourceDirectory.Data()).c_str()));
            }
        }

        const String cxxModeStr = parseResult.GetValue()["CXXMode"].AsString();
        CodeGen::Tool::CXXGenerationMode cxxMode = CodeGen::Tool::CXXGenerationMode::CPP;
        if (cxxModeStr.ToLower() == "inl")
        {
            cxxMode = CodeGen::Tool::CXXGenerationMode::INL;
        }

        CodeGen::Tool tool {
            workingDirectory,
            sourceDirectory,
            cxxOutputDirectory,
            csharpOutputDirectory,
            hypscriptOutputDirectory,
            excludeDirectories,
            excludeFiles,
            cxxMode
        };

        Result res = tool.Run();

        TaskSystem::GetInstance().Stop();

        if (res.HasError())
        {
            HYP_LOG(Tool, Error, "Tool execution failed: {}", res.GetError().GetMessage());

            return 1;
        }

        HYP_LOG(Tool, Info, "Complete");
    }
    else
    {
        HYP_LOG(Tool, Error, "Failed to parse arguments!\n\t{}", parseResult.GetError().GetMessage());

        return 1;
    }

    return 0;
}
