#version 460
#extension GL_GOOGLE_include_directive : require
#extension GL_EXT_ray_tracing : enable
#extension GL_EXT_scalar_block_layout : enable

#define DDGI

#include "../../include/defines.inc"
#include "../../include/noise.inc"
#include "../../include/packing.inc"

HYP_DESCRIPTOR_SAMPLER(DDGI, SamplerNearest) uniform sampler sampler_nearest;
HYP_DESCRIPTOR_SAMPLER(DDGI, SamplerLinear) uniform sampler sampler_linear;

#define texture_sampler sampler_linear
#define HYP_SAMPLER_NEAREST sampler_nearest
#define HYP_SAMPLER_LINEAR sampler_linear

#define HYP_DO_NOT_DEFINE_DESCRIPTOR_SETS

#include "../../include/scene.inc"
#include "../../include/shared.inc"
#include "../../include/noise.inc"
#include "../../include/Octahedron.glsl"
#include "../../include/env_probe.inc"

#undef HYP_DO_NOT_DEFINE_DESCRIPTOR_SETS

#include "../../include/rt/payload.inc"
#include "../../include/rt/probe/probe_uniforms.inc"

HYP_DESCRIPTOR_ACCELERATION_STRUCTURE(DDGI, TLAS) uniform accelerationStructureEXT tlas;

HYP_DESCRIPTOR_CBUFF(DDGI, DDGIConstants) uniform DDGIUniformBuffer
{
    DDGIConstants ddgiConstants;
};

HYP_DESCRIPTOR_SSBO(DDGI, ProbeRayData) buffer ProbeRayDataBuffer
{
    ProbeRayData probe_rays[];
};

HYP_DESCRIPTOR_CBUFF(DDGI, Lights) uniform Lights
{
    Light lights[MAX_LIGHTS];
};

#include "../../include/rt/probe/shared.inc"

HYP_DESCRIPTOR_CBUFF(DDGI, WorldsBuffer) uniform WorldsBuffer
{
    WorldShaderData world_shader_data;
};

#if HAS_ENV_PROBE
HYP_DESCRIPTOR_SSBO_DYNAMIC(DDGI, CurrentEnvProbe) readonly buffer CurrentEnvProbe { EnvProbe current_env_probe; };

#if ENV_PROBE_CUBEMAP
HYP_DESCRIPTOR_SRV(DDGI, EnvProbesTexture) uniform textureCubeArray envProbesTexture;
#else
HYP_DESCRIPTOR_SRV(DDGI, EnvProbesTexture) uniform texture2DArray envProbesTexture;
#endif

#endif

HYP_DESCRIPTOR_SRV(DDGI, ShadowMapsTextureArray) uniform texture2DArray shadow_maps;
HYP_DESCRIPTOR_SRV(DDGI, PointLightShadowMapsTextureArray) uniform textureCubeArray point_shadow_maps;

#include "../../include/shadows.inc"

layout(location = 0) rayPayloadEXT RayPayload payload;

#define RAY_OFFSET 0.025
#define NUM_BOUNCES 3

void SetProbeRayData(uvec2 coord, ProbeRayData ray_data)
{
    probe_rays[PROBE_RAY_DATA_INDEX(coord)] = ray_data;
}

struct RayBounceInfo
{
    vec4 throughput;
    vec4 emissive;
};

void main()
{
    const uvec2 coord = uvec2(gl_LaunchIDEXT.xy);
    
    const uint probe_index = coord.x;
    const uint ray_index = coord.y;
    
    vec3 direction = normalize(mat3(ddgiConstants.rotationMatrix) * SphericalFibonacci(ray_index, ddgiConstants.num_rays_per_probe));
    vec3 origin = ProbeIndexToWorldPosition(probe_index) + direction * RAY_OFFSET;
    
    uint flags = gl_RayFlagsOpaqueEXT;
    uint mask = 0xff;
    float tmin = RAY_OFFSET;
    float tmax = ddgiConstants.probe_distance;
    
    payload.throughput = vec4(1.0);
    payload.color = vec4(0.0);
    payload.distance = -1.0;
    
    uint ray_seed = InitRandomSeed(InitRandomSeed(coord.x, coord.y), world_shader_data.frame_counter % 256);

    ProbeRayData ray_data[NUM_BOUNCES];
    ray_data[0].color = vec4(0.0);
    
    RayBounceInfo bounces[NUM_BOUNCES];
    uint num_bounces = 0;

    for (int bounce_index = 0; bounce_index < NUM_BOUNCES; bounce_index++)
    {
        payload.distance = -1.0;

        vec3 normal = payload.normal;
        traceRayEXT(tlas, flags, mask, 0, 0, 0, origin, tmin, direction, tmax, 0);

        bounces[bounce_index].throughput = payload.throughput;
        bounces[bounce_index].emissive = payload.emissive;

        ray_data[bounce_index].color = vec4(0.0);
        ray_data[bounce_index].origin = vec4(origin, 1.0);
        ray_data[bounce_index].normal = vec4(payload.normal, 0.0);
        ray_data[bounce_index].direction_depth = vec4(direction, payload.distance);

        if (payload.distance < 0.0)
        {
            // hit the sky, sample the environment map
            if (current_env_probe.texture_index != ~0u)
            {
                uint probe_texture_index = max(0, min(current_env_probe.texture_index, HYP_MAX_BOUND_REFLECTION_PROBES - 1));

                bounces[bounce_index].emissive += EnvProbeSample(sampler_linear, envProbesTexture, probe_texture_index, direction, 0.0);
            }
            
            for (uint light_index = 0; light_index < ddgiConstants.num_bound_lights; light_index++)
            {
                const Light light = lights[light_index];

                // Only handle directional lights here
                if (light.type != HYP_LIGHT_TYPE_DIRECTIONAL)
                {
                    continue;
                }

                float shadow = 1.0;

                if (light.type == HYP_LIGHT_TYPE_DIRECTIONAL && bool(light.flags & LF_SHADOW))
                {
                    shadow = GetShadowStandard(light, origin);
                }

                const float cos_theta = max(dot(direction, normalize(light.position_intensity.xyz)), 0.0);
                bounces[bounce_index].emissive += light.color * light.position_intensity.w * shadow * cos_theta;
            }

            ++num_bounces;

            break;
        }
        
        vec3 hit_position = origin + direction * payload.distance;

        direction = normalize(RandomInHemisphere(
            vec3(RandomFloat(ray_seed), RandomFloat(ray_seed), RandomFloat(ray_seed)),
            payload.normal
        ));
        origin = hit_position + direction * RAY_OFFSET;

        ++num_bounces;
    }

    for (int bounce_index = int(num_bounces - 1); bounce_index >= 0; bounce_index--)
    {
        vec4 radiance = bounces[bounce_index].emissive;

        if (bounce_index != num_bounces - 1)
        {
            radiance += ray_data[bounce_index + 1].color * bounces[bounce_index].throughput;
        }

        // As the throughput is multiplied by the albedo, the probability of the ray getting discarded is higher
        float p = max(radiance.r, max(radiance.g, radiance.b));

        if (RandomFloat(ray_seed) > p)
        {
            break;
        }

        radiance /= max(p, 0.0001);
        
        ray_data[bounce_index].color = radiance;
    }

    SetProbeRayData(coord, ray_data[0]);
}
