#include <core/cli/CommandLine.hpp>

#include <core/logging/Logger.hpp>

#include <core/filesystem/FilePath.hpp>

#include <core/utilities/DeferredScope.hpp>

#include <core/threading/Thread.hpp>
#include <core/threading/Scheduler.hpp>
#include <core/threading/AtomicVar.hpp>
#include <core/threading/TaskSystem.hpp>
#include <core/threading/TaskThread.hpp>
#include <core/threading/Mutex.hpp>

#include <core/io/ByteWriter.hpp>
#include <core/io/BufferedByteReader.hpp>

#include <core/utilities/StringUtil.hpp>

#include <core/functional/Proc.hpp>

#include <core/memory/UniquePtr.hpp>

#include <generator/generators/CXXModuleGenerator.hpp>
#include <generator/generators/CSharpModuleGenerator.hpp>
#include <generator/generators/HypScriptModuleGenerator.hpp>

#include <parser/Parser.hpp>

#include <analyzer/Analyzer.hpp>

#include <util/ParseUtil.hpp>

#if !defined(HYP_BUILD_TOOL_VERSION_MAJOR) || !defined(HYP_BUILD_TOOL_VERSION_MINOR) || !defined(HYP_BUILD_TOOL_VERSION_PATCH)
#error "HYP_BUILD_TOOL_VERSION_MAJOR, HYP_BUILD_TOOL_VERSION_MINOR, and HYP_BUILD_TOOL_VERSION_PATCH must be defined"
#endif

namespace hyperion {

HYP_API Handle<Logger> g_logger;

namespace buildtool {

HYP_DEFINE_LOG_CHANNEL(BuildTool);

static constexpr bool JumboBuildEnabled = true;
static constexpr uint32 JumboBuildIdealFileSize = 64 * 1024;

static const String g_hypscriptPreamble = R"(// This file is autogenerated. Do not edit.

const INT8_MAX : int8 = 0x7F;
const INT16_MAX : int16 = 0x7FFF;
const INT32_MAX : int32 = 0x7FFFFFFF;
const INT64_MAX : int64 = 0x7FFFFFFFFFFFFFFF;
const UINT8_MAX : uint8 = 0xFFu;
const UINT16_MAX : uint16 = 0xFFFFu;
const UINT32_MAX : uint32 = 0xFFFFFFFFu;
const UINT64_MAX : uint64 = 0xFFFFFFFFFFFFFFFFu;
const FLT_MAX : float = 3.40282347e+38F;
const FLT_MIN : float = 1.17549435e-38F;
const FLT_EPSILON : float = 1.19209290e-07F;
const DBL_MAX : double = 1.7976931348623157e+308;
const DBL_MIN : double = 2.2250738585072014e-308;
const DBL_EPSILON : double = 2.2204460492503131e-16

)";

class WorkerThread : public TaskThread
{
public:
    WorkerThread(ThreadId id)
        : TaskThread(id)
    {
    }

    virtual ~WorkerThread() override = default;
};

class WorkerThreadPool : public TaskThreadPool
{
public:
    WorkerThreadPool()
        : TaskThreadPool(TypeWrapper<WorkerThread>(), "BuildTool_WorkerThread", 4)
    {
    }

    virtual ~WorkerThreadPool() override = default;
};

class HypBuildTool
{
public:
    enum class CXXGenerationMode
    {
        CPP,
        INL
    };

    HypBuildTool(
        const FilePath& workingDirectory,
        const FilePath& sourceDirectory,
        const FilePath& cxxOutputDirectory,
        const FilePath& csharpOutputDirectory,
        const FilePath& hypscriptOutputDirectory,
        const HashSet<FilePath>& excludeDirectories,
        const HashSet<FilePath>& excludeFiles,
        CXXGenerationMode cxxMode = CXXGenerationMode::CPP)
    {
        m_analyzer.SetWorkingDirectory(workingDirectory);
        m_analyzer.SetSourceDirectory(sourceDirectory);

        m_analyzer.SetCXXOutputDirectory(cxxOutputDirectory);
        m_analyzer.SetCSharpOutputDirectory(csharpOutputDirectory);
        m_analyzer.SetHypScriptOutputDirectory(hypscriptOutputDirectory);

        m_analyzer.SetExcludeDirectories(excludeDirectories);
        m_analyzer.SetExcludeFiles(excludeFiles);

        m_analyzer.SetGlobalDefines(GetGlobalDefines());
        m_analyzer.SetIncludePaths(GetIncludePaths());

        m_cxxMode = cxxMode;

        m_threadPool.Start();
    }

    ~HypBuildTool()
    {
        m_threadPool.Stop();
    }

    Result Run()
    {
        HYP_LOG(BuildTool, Info, "HypBuildTool v{}.{}.{}", HYP_BUILD_TOOL_VERSION_MAJOR, HYP_BUILD_TOOL_VERSION_MINOR, HYP_BUILD_TOOL_VERSION_PATCH);
        HYP_LOG(BuildTool, Info, "Running...");

        FindModules();

        Task processModules = ProcessModules();
        WaitWhileTaskRunning(processModules);

        Task buildClassTree = BuildClassTree();
        WaitWhileTaskRunning(buildClassTree);

        Task generateOutputFiles = GenerateOutputFiles();
        WaitWhileTaskRunning(generateOutputFiles);

        if (m_analyzer.GetState().HasErrors())
        {
            for (const AnalyzerError& error : m_analyzer.GetState().errors)
            {
                HYP_LOG(BuildTool, Error, "Error: {}", error.GetMessage());
            }

            return HYP_MAKE_ERROR(Error, "Build tool finished with errors");
        }

        // finally, add BuildToolOutput.inc to the output directory
        FilePath outputFilePath = m_analyzer.GetCXXOutputDirectory() / "BuildToolOutput.inc";
        FileByteWriter outputFileWriter(outputFilePath);
        if (!outputFileWriter.IsOpen())
        {
            return HYP_MAKE_ERROR(Error, "Failed to open output file: {}", outputFilePath);
        }

        // for parsing from scripts to enable rebuild triggering:
        outputFileWriter.WriteString("//! VERSION " + String::ToString(HYP_BUILD_TOOL_VERSION_MAJOR) + "." + String::ToString(HYP_BUILD_TOOL_VERSION_MINOR) + "." + String::ToString(HYP_BUILD_TOOL_VERSION_PATCH) + "\n\n");
        outputFileWriter.WriteString("// Copyright (c) No Tomorrow Games\n");
        outputFileWriter.WriteString("// This file is generated by the HypBuildTool. Do not edit manually.\n\n");
        outputFileWriter.WriteString("#pragma once\n\n");
        outputFileWriter.WriteString("#define HYP_BUILD_TOOL_VERSION_MAJOR " + String::ToString(HYP_BUILD_TOOL_VERSION_MAJOR) + "\n");
        outputFileWriter.WriteString("#define HYP_BUILD_TOOL_VERSION_MINOR " + String::ToString(HYP_BUILD_TOOL_VERSION_MINOR) + "\n");
        outputFileWriter.WriteString("#define HYP_BUILD_TOOL_VERSION_PATCH " + String::ToString(HYP_BUILD_TOOL_VERSION_PATCH) + "\n\n");

        outputFileWriter.WriteString("\n");
        outputFileWriter.Close();

        HYP_LOG(BuildTool, Info, "Build tool finished successfully");

        return {};
    }

private:
    HashMap<String, String> GetGlobalDefines() const
    {
        return {
            { "HYP_BUILDTOOL", "1" },
            { "HYP_VULKAN", "1" },
            { "HYP_CLASS(...)", "" },
            { "HYP_STRUCT(...)", "" },
            { "HYP_ENUM(...)", "" },
            { "HYP_FIELD(...)", "" },
            { "HYP_METHOD(...)", "" },
            { "HYP_PROPERTY(...)", "" },
            { "HYP_OBJECT_BODY(...)", "" },
            { "HYP_API", "" },
            { "HYP_EXPORT", "" },
            { "HYP_IMPORT", "" },
            { "HYP_FORCE_INLINE", "inline" },
            { "HYP_NODISCARD", "" }
        };
    }

    HashSet<String> GetIncludePaths() const
    {
        const FilePath& workingDirectory = m_analyzer.GetWorkingDirectory();

        return {
            workingDirectory / "src",
            workingDirectory / "include"
        };
    }

    void FindModules()
    {
        Proc<void(const FilePath&)> iterateFilesAndSubdirectories;

        iterateFilesAndSubdirectories = [&](const FilePath& dir)
        {
            for (const String& excludeDir : m_analyzer.GetExcludeDirectories())
            {
                const FilePath relativePath = FilePath(FileSystem::RelativePath(dir.Data(), m_analyzer.GetSourceDirectory().Data()).c_str());

                if (relativePath.StartsWith(excludeDir))
                {
                    return;
                }
            }

            Array<Module*> localModules;

            for (const FilePath& file : dir.GetAllFilesInDirectory())
            {
                if (file.EndsWith(".hpp"))
                {
                    const FilePath relativePath = FilePath(FileSystem::RelativePath(file.Data(), m_analyzer.GetSourceDirectory().Data()).c_str());

                    if (m_analyzer.GetExcludeFiles().Contains(relativePath))
                    {
                        continue;
                    }

                    localModules.PushBack(m_analyzer.AddModule(file));
                }
            }

            Array<FilePath> localSubdirectories = dir.GetSubdirectories();

            if (localSubdirectories.Empty())
            {
                return;
            }

            for (const FilePath& subdirectory : localSubdirectories)
            {
                iterateFilesAndSubdirectories(subdirectory);
            }
        };

        iterateFilesAndSubdirectories(m_analyzer.GetSourceDirectory());
    }

    Task<void> ProcessModules()
    {
        Task<void> task;

        TaskBatch* batch = new TaskBatch();
        batch->pool = &m_threadPool;
        batch->OnComplete
            .Bind([batch, promise = task.Promise()]()
                {
                    promise->Fulfill();

                    DeferDeleteTaskBatch(batch);
                })
            .Detach();

        for (const UniquePtr<Module>& mod : m_analyzer.GetModules())
        {
            batch->AddTask([this, mod = mod.Get()]()
                {
                    auto result = m_analyzer.ProcessModule(*mod);

                    if (result.HasError())
                    {
                        m_analyzer.AddError(result.GetError());

                        return;
                    }
                });
        }

        TaskSystem::GetInstance().EnqueueBatch(batch);

        return task;
    }

    Task<void> BuildClassTree()
    {
        return TaskSystem::GetInstance().Enqueue([this]()
            {
                Array<HypClassDefinition*> hypClassDefinitions;
                HashMap<String, uint32> hypClassDefinitionIds;

                for (auto& it : m_analyzer.GetBuiltinHypClasses())
                {
                    if (hypClassDefinitionIds.Contains(it.second.name))
                    {
                        m_analyzer.AddError(HYP_MAKE_ERROR(AnalyzerError, "Duplicate HypClassDefinition name found: {}", "<builtin>", 0, it.second.name));

                        continue;
                    }

                    Assert(it.second.staticIndex != -1); // builtins should have static indices assigned

                    const uint32 hypClassDefinitionId = uint32(hypClassDefinitions.Size());

                    hypClassDefinitionIds[it.second.name] = hypClassDefinitionId;
                    hypClassDefinitions.PushBack(&it.second);
                }

                // init ids and add dependency modules
                for (const UniquePtr<Module>& mod : m_analyzer.GetModules())
                {
                    HashSet<Module*> dependencyModules;

                    Proc<void(const HypClassDefinition& srcClassDef, const ASTType* type)> addDependenciesRecur;
                    addDependenciesRecur = [&](const HypClassDefinition& srcClassDef, const ASTType* type)
                    {
                        if (!type)
                        {
                            return;
                        }

                        if (type->isPointer)
                        {
                            addDependenciesRecur(srcClassDef, type->ptrTo.Get());
                            return;
                        }

                        if (type->isLvalueReference || type->isRvalueReference)
                        {
                            addDependenciesRecur(srcClassDef, type->refTo.Get());
                            return;
                        }

                        if (type->isArray)
                        {
                            addDependenciesRecur(srcClassDef, type->arrayOf.Get());
                            return;
                        }

                        if (type->isTemplate)
                        {
                            for (const RC<ASTTemplateArgument>& templateArgument : type->templateArguments)
                            {
                                Assert(templateArgument != nullptr);

                                if (templateArgument->type != nullptr)
                                {
                                    addDependenciesRecur(srcClassDef, templateArgument->type.Get());
                                }
                            }

                            return;
                        }

                        if (type->isFunction)
                        {
                            const ASTFunctionType* functionType = dynamic_cast<const ASTFunctionType*>(type);
                            Assert(functionType != nullptr);

                            addDependenciesRecur(srcClassDef, functionType->returnType.Get());

                            for (const RC<ASTMemberDecl>& param : functionType->parameters)
                            {
                                addDependenciesRecur(srcClassDef, param->type.Get());
                            }

                            return;
                        }

                        if (type->typeName.HasValue())
                        {
                            const HypClassDefinition* depHypClass = m_analyzer.FindHypClassDefinition(type->typeName->ToString(/* includeNamespace */ false));

                            if (depHypClass != nullptr && depHypClass->declModule != nullptr && depHypClass->declModule != mod.Get())
                            {
                                dependencyModules.Insert(depHypClass->declModule);
                            }
                        }
                    };

                    for (auto& it : mod->GetHypClasses())
                    {
                        for (HypMemberDefinition& definition : it.second.members)
                        {
                            addDependenciesRecur(it.second, definition.cxxType.Get());
                        }

                        if (hypClassDefinitionIds.Contains(it.second.name))
                        {
                            m_analyzer.AddError(HYP_MAKE_ERROR(AnalyzerError, "Duplicate HypClassDefinition name found: {}", mod->GetPath(), 0, it.second.name));

                            continue;
                        }

                        Assert(it.second.staticIndex == -1);
                        Assert(it.second.numDescendants == 0);

                        const uint32 hypClassDefinitionId = uint32(hypClassDefinitions.Size());

                        hypClassDefinitionIds[it.second.name] = hypClassDefinitionId;

                        hypClassDefinitions.PushBack(&it.second);
                    }

                    if (dependencyModules.Any())
                    {
                        for (Module* dependencyModule : dependencyModules)
                        {
                            mod->AddDependencyModule(dependencyModule);
                        }
                    }
                }

                Array<Array<uint32>, DynamicAllocator> derived;
                derived.Resize(hypClassDefinitions.Size());

                for (const HypClassDefinition* hypClassDefinition : hypClassDefinitions)
                {
                    const uint32 child = hypClassDefinitionIds.At(hypClassDefinition->name);

                    for (const String& baseClassName : hypClassDefinition->baseClassNames)
                    {
                        const auto parentIt = hypClassDefinitionIds.Find(baseClassName);

                        if (parentIt == hypClassDefinitionIds.End())
                        {
                            continue;
                        }

                        const uint32 parent = parentIt->second;
                        Assert(parent < hypClassDefinitions.Size());

                        derived[parent].PushBack(child);
                    }
                }

                Array<uint32> indeg;
                indeg.Resize(hypClassDefinitions.Size());

                for (const Array<uint32>& children : derived)
                {
                    for (uint32 child : children)
                    {
                        indeg[child]++;
                    }
                }

                Array<uint32> roots;

                for (SizeType i = 0; i < indeg.Size(); i++)
                {
                    if (indeg[i] == 0)
                    {
                        roots.PushBack(i);
                    }
                }

                Array<uint32> stack;
                stack.Reserve(hypClassDefinitions.Size());

                uint32 nextOut = 1; // 0 is reserved for HypObjectBase

                Proc<void(uint32)> topologicalSort;
                topologicalSort = [&](uint32 id)
                {
                    Assert(id < hypClassDefinitions.Size());

                    HypClassDefinition* hypClassDefinition = hypClassDefinitions[id];

                    uint32 start = nextOut;

                    // skip assignment for builtin HypObjectBase type (0)
                    const bool isBaseClass = hypClassDefinition->name == "HypObjectBase";

                    if (!isBaseClass)
                    {
                        hypClassDefinition->staticIndex = int(nextOut++);
                    }

                    stack.PushBack(id);

                    for (uint32 i : derived[id])
                    {
                        if (hypClassDefinitions[i]->staticIndex == -1)
                        {
                            topologicalSort(i);
                        }
                    }

                    stack.PopBack();

                    hypClassDefinition->numDescendants = nextOut - start - 1;

                    if (!isBaseClass)
                    {
                        hypClassDefinition->staticIndex = int(start + 1);
                    }
                };

                for (uint32 root : roots)
                {
                    topologicalSort(root);
                }
            });
    }

    Task<void> GenerateOutputFiles()
    {
        Assert(m_analyzer.GetCXXOutputDirectory().MkDir(), "Failed to create C++ output directory: {}", m_analyzer.GetCXXOutputDirectory());

        Task<void> task;

        TaskBatch* batch = new TaskBatch();
        batch->pool = &m_threadPool;
        batch->OnComplete
            .Bind([batch, promise = task.Promise()]()
                {
                    promise->Fulfill();

                    DeferDeleteTaskBatch(batch);
                })
            .Detach();

        RC<Module> builtinsModule = MakeRefCountedPtr<Module>(FilePath());

        // add all builtins to a fake module for generation
        for (auto& it : m_analyzer.GetBuiltinHypClasses())
        {
            builtinsModule->GetHypClasses().Set(it.second.name, it.second);
        }

        if (m_analyzer.GetCSharpOutputDirectory().Any())
        {
            Assert(m_analyzer.GetCSharpOutputDirectory().MkDir(), "Failed to create C# output directory: {}", m_analyzer.GetCSharpOutputDirectory());

            RC<CSharpModuleGenerator> csharpModuleGenerator = MakeRefCountedPtr<CSharpModuleGenerator>();

            if (builtinsModule->GetHypClasses().Any())
            {
                // generate builtins first
                batch->AddTask([this, csharpModuleGenerator, builtinsModule]()
                    {
                        if (Result res = csharpModuleGenerator->Generate(m_analyzer, *builtinsModule); res.HasError())
                        {
                            m_analyzer.AddError(AnalyzerError(res.GetError(), FilePath("<builtins>")));
                        }
                    });
            }

            for (const UniquePtr<Module>& mod : m_analyzer.GetModules())
            {
                if (mod->GetHypClasses().Empty())
                {
                    continue;
                }

                // csharp modules can be processed async from C++ modules
                batch->AddTask([this, csharpModuleGenerator, &mod = *mod]()
                    {
                        if (Result res = csharpModuleGenerator->Generate(m_analyzer, mod); res.HasError())
                        {
                            m_analyzer.AddError(AnalyzerError(res.GetError(), mod.GetPath()));
                        }
                    });
            }
        }

        if (m_analyzer.GetHypScriptOutputDirectory().Any())
        {
            Assert(m_analyzer.GetHypScriptOutputDirectory().MkDir(), "Failed to create HypScript output directory: {}", m_analyzer.GetHypScriptOutputDirectory());

            RC<HypScriptModuleGenerator> hypscriptModuleGenerator = MakeRefCountedPtr<HypScriptModuleGenerator>();

            // for hypscript, we want to generate all modules and then merge them into one file
            // but we need to sort modules topologically to ensure dependencies come first

            FileByteWriter hypscriptModuleWriter(m_analyzer.GetHypScriptOutputDirectory() / "Lib.hyp");

            if (!hypscriptModuleWriter.IsOpen())
            {
                m_analyzer.AddError(HYP_MAKE_ERROR(AnalyzerError, "Failed to open HypScript output file: {}", {}, -1, m_analyzer.GetHypScriptOutputDirectory() / "Lib.hyp"));
            }

            hypscriptModuleWriter.WriteString(*g_hypscriptPreamble);

            if (builtinsModule->GetHypClasses().Any())
            {
                // generate builtins first
                if (Result res = hypscriptModuleGenerator->Generate(m_analyzer, *builtinsModule, hypscriptModuleWriter); res.HasError())
                {
                    m_analyzer.AddError(AnalyzerError(res.GetError(), FilePath("<builtins>")));
                }
            }

            Array<Module*> sortedModules = SortModulesTopologically();

            for (Module* mod : sortedModules)
            {
                if (mod->GetHypClasses().Empty())
                {
                    continue;
                }

                MemoryByteWriter writer;

                if (Result res = hypscriptModuleGenerator->Generate(m_analyzer, *mod, writer); res.HasError())
                {
                    m_analyzer.AddError(AnalyzerError(res.GetError(), mod->GetPath()));

                    continue;
                }

                if (writer.Position() == 0) // nothing was written
                {
                    continue;
                }

                hypscriptModuleWriter.Write(writer.GetBuffer());
            }

            hypscriptModuleWriter.Close();
        }

        RC<CXXModuleGenerator> cxxModuleGenerator = MakeRefCountedPtr<CXXModuleGenerator>();

        // Generate the HypClassDecl header and implementation files (shared by both modes)
        {
            FilePath hypClassDeclHeaderPath = m_analyzer.GetCXXOutputDirectory() / "HypClassDecls.inc";
            FileByteWriter hypClassDeclWriter(hypClassDeclHeaderPath);

            if (!hypClassDeclWriter.IsOpen())
            {
                m_analyzer.AddError(HYP_MAKE_ERROR(AnalyzerError, "Failed to open HypClassDecl header file: {}", {}, -1, hypClassDeclHeaderPath));
            }
            else
            {
                if (Result res = cxxModuleGenerator->GenerateHypClassDeclHeader(m_analyzer, hypClassDeclWriter); res.HasError())
                {
                    m_analyzer.AddError(AnalyzerError(res.GetError(), hypClassDeclHeaderPath));
                }

                hypClassDeclWriter.Close();
            }
        }

        {
            FilePath hypClassDeclImplPath = m_analyzer.GetCXXOutputDirectory() / "HypClassDecls.cpp";
            FileByteWriter hypClassDeclImplWriter(hypClassDeclImplPath);

            if (!hypClassDeclImplWriter.IsOpen())
            {
                m_analyzer.AddError(HYP_MAKE_ERROR(AnalyzerError, "Failed to open HypClassDecl implementation file: {}", {}, -1, hypClassDeclImplPath));
            }
            else
            {
                if (Result res = cxxModuleGenerator->GenerateHypClassDeclImplementation(m_analyzer, hypClassDeclImplWriter); res.HasError())
                {
                    m_analyzer.AddError(AnalyzerError(res.GetError(), hypClassDeclImplPath));
                }

                hypClassDeclImplWriter.Close();
            }
        }

        if (m_cxxMode == CXXGenerationMode::INL)
        {
            // Pre-scan for duplicate flattened .inl filenames (e.g., Foo.generated.inl)
            HashMap<String, FilePath> seenInlNames; // maps inl filename to first header path encountered
            HashSet<String> duplicateInlNames;      // set of filenames that collide

            for (const UniquePtr<Module>& mod : m_analyzer.GetModules())
            {
                if (mod->GetHypClasses().Empty())
                {
                    continue;
                }

                const FilePath& headerPath = mod->GetPath();
                if (!headerPath.Any())
                {
                    continue;
                }

                const String stem = StringUtil::StripExtension(headerPath.Basename());
                const String inlFilename = stem + ".generated.inl";

                if (seenInlNames.Contains(inlFilename))
                {
                    const FilePath& firstHeaderPath = seenInlNames.At(inlFilename);

                    if (!duplicateInlNames.Contains(inlFilename))
                    {
                        duplicateInlNames.Insert(inlFilename);
                        HYP_LOG(BuildTool, Error, "Duplicate inline output filename '{}' would be generated from:\n - {}\n - {}", inlFilename, firstHeaderPath, headerPath);

                        m_analyzer.AddError(HYP_MAKE_ERROR(AnalyzerError, "Duplicate inline output filename detected in flattened inline mode: {} vs {}", inlFilename, {}, -1, firstHeaderPath, headerPath));
                    }
                    else
                    {
                        // Additional duplicate beyond the first two
                        HYP_LOG(BuildTool, Error, "Duplicate inline output filename '{}' also produced by: {} (first seen at {})", inlFilename, headerPath, firstHeaderPath);
                        m_analyzer.AddError(HYP_MAKE_ERROR(AnalyzerError, "Duplicate inline output filename detected in flattened inline mode", {}, -1, headerPath));
                    }
                }
                else
                {
                    seenInlNames[inlFilename] = headerPath;
                }
            }

            // Inline mode: generate one small cpp for builtins and per-module .inl files
            if (builtinsModule->GetHypClasses().Any())
            {
                FilePath builtinsCppPath = m_analyzer.GetCXXOutputDirectory() / "Builtins.cpp";
                FileByteWriter builtinsWriter(builtinsCppPath);

                if (!builtinsWriter.IsOpen())
                {
                    m_analyzer.AddError(HYP_MAKE_ERROR(AnalyzerError, "Failed to open builtins output file: {}", {}, -1, builtinsCppPath));
                }
                else
                {
                    builtinsWriter.WriteString(GetGeneratedFilePreamble(String::empty));
                    builtinsWriter.WriteString("#include <core/reflection/HypClassUtils.hpp>\n");
                    if (Result res = cxxModuleGenerator->Generate(m_analyzer, *builtinsModule, builtinsWriter); res.HasError())
                    {
                        m_analyzer.AddError(AnalyzerError(res.GetError(), FilePath("<builtins>")));
                    }
                    builtinsWriter.Close();
                }
            }

            for (const UniquePtr<Module>& mod : m_analyzer.GetModules())
            {
                if (mod->GetHypClasses().Empty())
                {
                    continue;
                }

                // Skip modules that would generate a duplicate flattened inline filename
                {
                    const FilePath& headerPath = mod->GetPath();
                    if (headerPath.Any())
                    {
                        const String stem = StringUtil::StripExtension(headerPath.Basename());
                        const String inlFilename = stem + ".generated.inl";
                        if (duplicateInlNames.Contains(inlFilename))
                        {
                            // Error already recorded in the pre-scan; skip generating/including to avoid overwrite
                            continue;
                        }
                    }
                }

                FilePath inlPath = cxxModuleGenerator->GetInlineOutputFilePath(m_analyzer, *mod);
                Assert(inlPath.BasePath().MkDir(), "Failed to create output directory for {}", inlPath);

                FileByteWriter inlWriter(inlPath);
                if (!inlWriter.IsOpen())
                {
                    m_analyzer.AddError(HYP_MAKE_ERROR(AnalyzerError, "Failed to open inline output file: {}", {}, -1, inlPath));
                    continue;
                }

                // Generate inline content without includes
                if (Result res = cxxModuleGenerator->GenerateInline(m_analyzer, *mod, inlWriter); res.HasError())
                {
                    m_analyzer.AddError(AnalyzerError(res.GetError(), mod->GetPath()));
                    inlWriter.Close();
                    continue;
                }

                inlWriter.Close();

                // Inject include into the corresponding .cpp file
                Result res = InjectInlineIncludeForModule(*mod, inlPath);

                if (res.HasError())
                {
                    m_analyzer.AddError(AnalyzerError(res.GetError(), mod->GetPath()));
                    continue;
                }
            }

            TaskSystem::GetInstance().EnqueueBatch(batch);

            return task;
        }

        static constexpr uint32 idealCxxModuleFileSize = JumboBuildEnabled ? JumboBuildIdealFileSize : 1;

        uint32 fileIndex = 0;
        char filenameBuffer[256] = {};

        FileByteWriter* cxxModuleWriter = nullptr;

        auto toLetters = [](uint32 idx, char* dst, SizeType cap)
        {
            char buf[32];
            SizeType n = 0;

            ++idx;
            while (idx)
            {
                uint32 r = (idx - 1) % 26;
                buf[n++] = char('A' + r);
                idx = (idx - 1) / 26;
            }

            if (n + 4 >= cap)
            {
                return false;
            }

            for (SizeType i = 0; i < n; ++i)
            {
                dst[i] = buf[n - 1 - i];
            }

            dst[n] = '\0';

            return true;
        };

        auto updateFilenameBuffer = [&]()
        {
            Assert(toLetters(fileIndex, filenameBuffer, sizeof(filenameBuffer)));

            std::strcat(filenameBuffer, ".cpp");

            ++fileIndex;
        };

        if (builtinsModule->GetHypClasses().Any())
        {
            // generate builtins first
            updateFilenameBuffer();

            cxxModuleWriter = new FileByteWriter(m_analyzer.GetCXXOutputDirectory() / filenameBuffer);

            cxxModuleWriter->WriteString(GetGeneratedFilePreamble(String::empty));

            // add main required header that is shared across all generated modules.
            cxxModuleWriter->WriteString("#include <core/reflection/HypClassUtils.hpp>\n");

            if (Result res = cxxModuleGenerator->Generate(m_analyzer, *builtinsModule, *cxxModuleWriter); res.HasError())
            {
                m_analyzer.AddError(AnalyzerError(res.GetError(), FilePath("<builtins>")));
            }
        }

        for (const UniquePtr<Module>& mod : m_analyzer.GetModules())
        {
            if (mod->GetHypClasses().Empty())
            {
                continue;
            }

            if (!cxxModuleWriter || cxxModuleWriter->Position() >= idealCxxModuleFileSize)
            {
                if (cxxModuleWriter)
                {
                    cxxModuleWriter->Close();
                    delete cxxModuleWriter;
                }

                updateFilenameBuffer();

                cxxModuleWriter = new FileByteWriter(m_analyzer.GetCXXOutputDirectory() / filenameBuffer);

                cxxModuleWriter->WriteString(GetGeneratedFilePreamble(FilePath::Relative(mod->GetPath(), m_analyzer.GetSourceDirectory())));

                // add main required header that is shared across all generated modules.
                cxxModuleWriter->WriteString("#include <core/reflection/HypClassUtils.hpp>\n");
            }

            if (Result res = cxxModuleGenerator->Generate(m_analyzer, *mod, *cxxModuleWriter); res.HasError())
            {
                m_analyzer.AddError(AnalyzerError(res.GetError(), mod->GetPath()));
            }
        }

        if (cxxModuleWriter != nullptr)
        {
            cxxModuleWriter->Close();
            delete cxxModuleWriter;
        }

        TaskSystem::GetInstance().EnqueueBatch(batch);

        return task;
    }

    Result InjectInlineIncludeForModule(const Module& mod, const FilePath& inlPath)
    {
        // Compute expected source file path by replacing extension with .cpp (try variants)
        const FilePath& headerPath = mod.GetPath();
        if (!headerPath.Any())
        {
            return {}; // nothing to do
        }

        const String stem = StringUtil::StripExtension(headerPath.Basename());
        const FilePath baseDir = headerPath.BasePath();

        const FilePath cxxPath = baseDir / (stem + ".cpp");
        if (!cxxPath.Exists() || cxxPath.IsDirectory())
        {
            // No implementation file exists in src; create a small generated .cpp that includes the header and the .inl
            const FilePath relHeaderPath = FilePath::Relative(headerPath, m_analyzer.GetSourceDirectory());

            const FilePath genCppPath = inlPath.BasePath() / (stem + ".generated.cpp");
            Assert(genCppPath.BasePath().MkDir(), "Failed to create output directory for {}", genCppPath);

            // Compute include path for .inl relative to generated dir
            const FilePath relInlPathForGen = FilePath::Relative(inlPath, m_analyzer.GetCXXOutputDirectory());

            FileByteWriter writer { genCppPath };
            if (!writer.IsOpen())
            {
                return HYP_MAKE_ERROR(Error, "Failed to open generated implementation file '{}' for writing", genCppPath);
            }

            writer.WriteString(GetGeneratedFilePreamble(FilePath::Relative(headerPath, m_analyzer.GetSourceDirectory())));
            writer.WriteString(HYP_FORMAT("#include <{}>\n", relHeaderPath.ReplaceAll("\\", "/")));

            // Include dependency module headers (relative to source directory), like the non-inline path
            if (mod.GetDependencyModules().Any())
            {
                for (Module* dependencyModule : mod.GetDependencyModules())
                {
                    Assert(dependencyModule != nullptr);

                    if (!dependencyModule->GetPath().Any())
                    {
                        HYP_LOG(BuildTool, Error, "Dependency module has no path! Skipping include.");
                        continue;
                    }

                    FilePath relDepPath = FilePath::Relative(dependencyModule->GetPath(), m_analyzer.GetSourceDirectory());
                    String includeDepPathStr = relDepPath.Data();
                    writer.WriteString(HYP_FORMAT("#include <{}>\n", includeDepPathStr.ReplaceAll("\\", "/")));
                }

                writer.WriteString("\n");
            }

            writer.WriteString(HYP_FORMAT("#include <{}>\n", relInlPathForGen.ReplaceAll("\\", "/")));
            writer.Close();

            return {};
        }

        // Compute include path relative to generated include root
        const FilePath relInlPath = FilePath::Relative(inlPath, m_analyzer.GetCXXOutputDirectory());

        const String includeLine = HYP_FORMAT("#include <{}>", relInlPath.ReplaceAll("\\", "/"));

        // Read source file lines
        FileBufferedReaderSource source { cxxPath };

        if (!source.IsOK())
        {
            return HYP_MAKE_ERROR(Error, "Failed to open source file '{}' for reading during inline include injection", cxxPath);
        }

        BufferedByteReader reader { &source };

        Array<String> lines = reader.ReadAllLines();

        for (String& line : lines)
        {
            if (line.Contains(includeLine))
            {
                // Already included; don't write to file to avoid forcing unnecessary recompile
                return {};
            }
        }

        // To determine insertion point,
        // - Prefer after the last #include at preprocessor depth 0
        // - Otherwise, before the first 'namespace' encountered at depth 0
        // - Never insert while within a preprocessor conditional block

        auto isPPIf = [](const String& s)
        {
            return s.StartsWith("#if") || s.StartsWith("#ifdef") || s.StartsWith("#ifndef");
        };

        auto isPPEndif = [](const String& s)
        {
            return s.StartsWith("#endif");
        };

        auto isPPElseElif = [](const String& s)
        {
            return s.StartsWith("#else") || s.StartsWith("#elif");
        };

        SizeType lastIncludeAtDepth0 = SizeType(-1);
        SizeType firstNamespaceAtDepth0 = SizeType(-1);
        SizeType firstNonPPAtDepth0 = SizeType(-1);
        int preprocessorDepth = 0;

        for (SizeType i = 0; i < lines.Size(); ++i)
        {
            const String line = lines[i].Trimmed();

            // preprocessor depth
            if (line.StartsWith("#"))
            {
                if (isPPIf(line))
                {
                    ++preprocessorDepth;
                }
                else if (isPPEndif(line))
                {
                    if (preprocessorDepth > 0)
                    {
                        --preprocessorDepth;
                    }
                }
                else if (isPPElseElif(line))
                {
                    // depth unchanged
                }
            }

            // Record last include at depth 0
            if (preprocessorDepth == 0 && line.StartsWith("#include"))
            {
                lastIncludeAtDepth0 = i;
            }

            // Record first non-preprocessor, non-empty line at depth 0
            if (preprocessorDepth == 0 && line.Any() && !line.StartsWith("#") && firstNonPPAtDepth0 == SizeType(-1))
            {
                firstNonPPAtDepth0 = i;

                if (line.StartsWith("namespace") && firstNamespaceAtDepth0 == SizeType(-1))
                {
                    firstNamespaceAtDepth0 = i;
                    break; // don't insert within namespace; earlier is better
                }
            }
        }

        SizeType insertIndex = SizeType(-1);

        if (lastIncludeAtDepth0 != SizeType(-1))
        {
            insertIndex = lastIncludeAtDepth0 + 1;
        }
        else if (firstNamespaceAtDepth0 != SizeType(-1))
        {
            insertIndex = firstNamespaceAtDepth0; // before namespace
        }
        else if (firstNonPPAtDepth0 != SizeType(-1))
        {
            insertIndex = firstNonPPAtDepth0; // before first code at depth 0
        }
        else
        {
            // Fallback: append at end (should be depth 0 by now)
            insertIndex = lines.Size();
        }

        if (insertIndex <= 0)
        {
            lines.Insert(lines.Begin(), includeLine);
        }
        else if (insertIndex >= lines.Size())
        {
            lines.PushBack(includeLine);
        }
        else
        {
            lines.Insert(lines.Begin() + insertIndex, includeLine);
        }

        // Write back to file
        FileByteWriter writer { cxxPath };
        if (!writer.IsOpen())
        {
            return HYP_MAKE_ERROR(Error, "Failed to open source file '{}' for writing during inline include injection", cxxPath);
        }

        const String joined = String::Join(lines, '\n') + '\n';
        writer.WriteString(joined);
        writer.Close();

        return {};
    }

    Array<Module*> SortModulesTopologically()
    {
        // Build a map from class names to modules that contain them
        HashMap<String, Module*> classToModule;
        HashMap<Module*, uint32> moduleToIndex;
        Array<Module*> moduleArray;

        for (const UniquePtr<Module>& mod : m_analyzer.GetModules())
        {
            if (mod->GetHypClasses().Empty())
            {
                continue;
            }

            const uint32 moduleIndex = uint32(moduleArray.Size());
            moduleToIndex[mod.Get()] = moduleIndex;
            moduleArray.PushBack(mod.Get());

            for (const auto& classEntry : mod->GetHypClasses())
            {
                classToModule[classEntry.second.name] = mod.Get();
            }
        }

        // Build dependency graph between modules
        const SizeType numModules = moduleArray.Size();
        Array<Array<uint32>> dependents(numModules); // dependents[i] contains modules that depend on module i
        Array<uint32> inDegree;                      // number of modules that this module depends on
        inDegree.Resize(numModules);

        // Initialize inDegree to 0
        for (SizeType i = 0; i < numModules; i++)
        {
            inDegree[i] = 0;
        }

        for (SizeType i = 0; i < numModules; i++)
        {
            Module* currentModule = moduleArray[i];

            // Collect all base classes used by this module
            HashSet<Module*> dependencyModules;

            for (const auto& classEntry : currentModule->GetHypClasses())
            {
                const HypClassDefinition& classDef = classEntry.second;

                for (const String& baseClassName : classDef.baseClassNames)
                {
                    auto it = classToModule.Find(baseClassName);
                    if (it != classToModule.End() && it->second != currentModule)
                    {
                        dependencyModules.Insert(it->second);
                    }
                }
            }

            // Update dependency graph: currentModule depends on dependencyModules
            // So dependencyModule should come before currentModule
            for (Module* depModule : dependencyModules)
            {
                const uint32 depModuleIndex = moduleToIndex.At(depModule);
                dependents[depModuleIndex].PushBack(i); // depModule has currentModule as dependent
                inDegree[i]++;                          // currentModule has one more dependency
            }
        }

        Array<uint32> result;
        Array<uint32> queue;

        // Find all modules with no dependencies
        for (SizeType i = 0; i < numModules; i++)
        {
            if (inDegree[i] == 0)
            {
                queue.PushBack(i);
            }
        }

        while (!queue.Empty())
        {
            const uint32 currentIndex = queue.PopBack();
            result.PushBack(currentIndex);

            // Remove this module from dependency graph and check its dependents
            for (uint32 dependentIndex : dependents[currentIndex])
            {
                inDegree[dependentIndex]--;
                if (inDegree[dependentIndex] == 0)
                {
                    queue.PushBack(dependentIndex);
                }
            }
        }

        // Check for cycles
        if (result.Size() != numModules)
        {
            HYP_LOG(BuildTool, Warning, "Circular dependency detected in modules! Some modules may be in incorrect order.");

            // Add remaining modules to avoid missing any
            for (SizeType i = 0; i < numModules; i++)
            {
                if (inDegree[i] > 0)
                {
                    result.PushBack(i);
                }
            }
        }

        // Convert indices back to module pointers
        Array<Module*> sortedModules;
        sortedModules.Reserve(result.Size());

        for (uint32 index : result)
        {
            sortedModules.PushBack(moduleArray[index]);
        }

        return sortedModules;
    }

    void LogGeneratedClasses() const
    {
        for (const UniquePtr<Module>& mod : m_analyzer.GetModules())
        {
            for (const Pair<String, HypClassDefinition>& hypClass : mod->GetHypClasses())
            {
                HYP_LOG(BuildTool, Info, "Class: {} -> {}", hypClass.first, hypClass.second.staticIndex);

                // Log out all members
                for (const HypMemberDefinition& hypMember : hypClass.second.members)
                {
                    if (!hypMember.cxxType)
                    {
                        continue;
                    }

                    json::JSONValue json;
                    hypMember.cxxType->ToJSON(json);

                    HYP_LOG(BuildTool, Info, "\tMember: {}\t{}", hypMember.name, json.ToString(true));
                }
            }
        }
    }

    void WaitWhileTaskRunning(const Task<void>& task)
    {
        Threads::AssertOnThread(g_mainThread);

        Assert(task.IsValid());

        while (!task.IsCompleted())
        {
            Threads::Sleep(100);
        }
    }

    // Setup a task to delete the batch
    // Use when deleting the batch inline would cause an issue due to destructing a mutex that is currently locked.
    static void DeferDeleteTaskBatch(TaskBatch* batch)
    {
        if (!batch)
        {
            return;
        }

        TaskSystem::GetInstance().Enqueue([batch]()
            {
                delete batch;
            },
            TaskThreadPoolName::THREAD_POOL_BACKGROUND, TaskEnqueueFlags::FIRE_AND_FORGET);
    }

    WorkerThreadPool m_threadPool;
    Analyzer m_analyzer;
    CXXGenerationMode m_cxxMode = CXXGenerationMode::INL;
};

} // namespace buildtool
} // namespace hyperion

using namespace hyperion;
using namespace buildtool;

int main(int argc, char** argv)
{
    Threads::SetCurrentThreadId(g_mainThread);

    static Logger s_buildToolLogger;

    g_logger.ptr = &s_buildToolLogger;
    HYP_DEFER({ g_logger.ptr = nullptr; });

    LogChannelRegistrar::GetInstance().RegisterAll();

    CommandLineArgumentDefinitions definitions;
    definitions.Add("WorkingDirectory", "", "", CommandLineArgumentFlags::REQUIRED, CommandLineArgumentType::STRING);
    definitions.Add("SourceDirectory", "", "", CommandLineArgumentFlags::REQUIRED, CommandLineArgumentType::STRING);
    definitions.Add("CXXOutputDirectory", "", "", CommandLineArgumentFlags::REQUIRED, CommandLineArgumentType::STRING);
    definitions.Add("CSharpOutputDirectory", "", "", CommandLineArgumentFlags::NONE, CommandLineArgumentType::STRING, /* defaultValue */ String::empty);
    definitions.Add("HypScriptOutputDirectory", "", "", CommandLineArgumentFlags::NONE, CommandLineArgumentType::STRING, /* defaultValue */ String::empty);
    definitions.Add("ExcludeDirectories", "", "", CommandLineArgumentFlags::NONE, CommandLineArgumentType::STRING);
    definitions.Add("ExcludeFiles", "", "", CommandLineArgumentFlags::NONE, CommandLineArgumentType::STRING);
    definitions.Add("Mode", "m", "", CommandLineArgumentFlags::NONE, Array<String> { "ParseHeaders" }, String("ParseHeaders"));
    definitions.Add("CXXMode", "", "C++ code generation mode (Cpp or Inl)", CommandLineArgumentFlags::NONE, Array<String> { "Cpp", "Inl" }, String("Inl"));

    CommandLineParser commandLineParser { &definitions };

    if (auto parseResult = commandLineParser.Parse(argc, argv))
    {
        TaskSystem::GetInstance().Start();

        const FilePath workingDirectory = FilePath(parseResult.GetValue()["WorkingDirectory"].AsString());

        if (!workingDirectory.IsDirectory())
        {
            HYP_LOG(BuildTool, Error, "Working directory is not a directory: {}", workingDirectory);

            return 1;
        }

        const FilePath sourceDirectory = FilePath(parseResult.GetValue()["SourceDirectory"].AsString());

        if (!sourceDirectory.IsDirectory())
        {
            HYP_LOG(BuildTool, Error, "Source directory is not a directory: {}", sourceDirectory);

            return 1;
        }

        const FilePath cxxOutputDirectory = FilePath(parseResult.GetValue()["CXXOutputDirectory"].AsString());
        const FilePath csharpOutputDirectory = FilePath(parseResult.GetValue()["CSharpOutputDirectory"].AsString());
        const FilePath hypscriptOutputDirectory = FilePath(parseResult.GetValue()["HypScriptOutputDirectory"].AsString());

        HashSet<FilePath> excludeDirectories;
        HashSet<FilePath> excludeFiles;

        if (parseResult.GetValue().Contains("ExcludeDirectories"))
        {
            const json::JSONArray excludeDirectoriesJson = parseResult.GetValue()["ExcludeDirectories"].ToArray();

            for (const json::JSONValue& value : excludeDirectoriesJson)
            {
                excludeDirectories.Insert(FilePath(FileSystem::RelativePath(value.ToString().Data(), sourceDirectory.Data()).c_str()));
            }
        }

        if (parseResult.GetValue().Contains("ExcludeFiles"))
        {
            const json::JSONArray excludeFilesJson = parseResult.GetValue()["ExcludeFiles"].ToArray();

            for (const json::JSONValue& value : excludeFilesJson)
            {
                excludeFiles.Insert(FilePath(FileSystem::RelativePath(value.ToString().Data(), sourceDirectory.Data()).c_str()));
            }
        }

        const String cxxModeStr = parseResult.GetValue()["CXXMode"].AsString();
        buildtool::HypBuildTool::CXXGenerationMode cxxMode = buildtool::HypBuildTool::CXXGenerationMode::CPP;
        if (cxxModeStr.ToLower() == "inl")
        {
            cxxMode = buildtool::HypBuildTool::CXXGenerationMode::INL;
        }

        buildtool::HypBuildTool buildTool {
            workingDirectory,
            sourceDirectory,
            cxxOutputDirectory,
            csharpOutputDirectory,
            hypscriptOutputDirectory,
            excludeDirectories,
            excludeFiles,
            cxxMode
        };

        Result res = buildTool.Run();

        TaskSystem::GetInstance().Stop();

        if (res.HasError())
        {
            return 1;
        }
    }
    else
    {
        HYP_LOG(BuildTool, Error, "Failed to parse arguments!\n\t{}", parseResult.GetError().GetMessage());

        return 1;
    }

    return 0;
}
