#include <script/HypScript.hpp>

#include <script/vm/Stream.hpp>

#include <script/compiler/emit/BytecodeChunk.hpp>
#include <script/compiler/emit/InstructionStream.hpp>
#include <script/compiler/emit/Instruction.hpp>
#include <script/compiler/emit/codegen/CodeGenerator.hpp>

#include <script/compiler/Module.hpp>
#include <script/compiler/SemanticAnalyzer.hpp>
#include <script/compiler/Optimizer.hpp>
#include <script/compiler/Lexer.hpp>
#include <script/compiler/Parser.hpp>
#include <script/compiler/Compiler.hpp>

#include <script/compiler/dis/DecompilationUnit.hpp>

#include <script/compiler/AstPrintVisitor.hpp>

#include <script/vm/Interpreter.hpp>

#include <core/reflection/Class.hpp>
#include <core/reflection/HypMethod.hpp>
#include <core/reflection/Field.hpp>
#include <core/reflection/HypMemberFwd.hpp>
#include <core/reflection/ClassRegistry.hpp>

#include <core/io/BufferedByteReader.hpp>

#include <core/logging/Logger.hpp>
#include <core/logging/LogChannels.hpp>

#include <core/utilities/Format.hpp>
#include <core/utilities/Result.hpp>

#include <iostream>

namespace hyperion {

// #define HYP_PRINT_AST

HYP_DEFINE_LOG_CHANNEL(HypScript);

#pragma region HypScriptImpl

struct HypScriptImpl
{
    CompilationUnit globalCompilationUnit;
    Script_Interpreter* vm;
    Script_Instance* globalInstance;

    HypScriptImpl()
        : vm(new Script_Interpreter()),
          globalInstance(nullptr)
    {
    }

    HypScriptImpl(const HypScriptImpl& other) = delete;
    HypScriptImpl& operator=(const HypScriptImpl& other) = delete;

    ~HypScriptImpl()
    {
        if (globalInstance)
        {
            delete globalInstance;
            globalInstance = nullptr;
        }

        delete vm;
    }
};

#pragma endregion HypScriptImpl

/// Initialize the `Lib` script which is used to call into HypScript code from C++.
static Result InitializeHypScriptLib(HypScript& hs)
{
    // create the global script instance using Lib.hyp (generated by HypBuildTool)
    static const FilePath s_libPath = CoreApi_GetExecutablePath() / "Lib.hyp";

    FileBufferedReaderSource source { s_libPath };
    BufferedByteReader reader { &source };

    if (!reader.IsOpen())
    {
        return HYP_MAKE_ERROR(Error, "Failed to open Lib.hyp at path '{}'! Did the build tool run correctly?", s_libPath);
    }

    ByteBuffer byteBuffer = reader.ReadBytes();

    SourceFile sourceFile(s_libPath, byteBuffer.Size());
    sourceFile.ReadIntoBuffer(byteBuffer);

    ErrorList errorList;

    Script_Instance* pInstance = hs.Compile(sourceFile, errorList);

    if (errorList.HasFatalErrors())
    {
        return HYP_MAKE_ERROR(Error, "Failed to compile Lib.hyp! The script system will not function correctly.");
    }

    Assert(pInstance != nullptr);

    // run the main script to initialize classes, functions, etc.
    hs.Run(pInstance);

    return {};
}

HypScript& HypScript::GetInstance()
{
    static HypScript s_hypScriptInstance;

    return s_hypScriptInstance;
}

HypScript::HypScript()
    : m_impl(MakePimpl<HypScriptImpl>())
{
}

HypScript::~HypScript() = default;

Script_Interpreter* HypScript::GetVM() const
{
    return m_impl->vm;
}

Script_Instance* HypScript::GetGlobalInstance() const
{
    return m_impl->globalInstance;
}

void HypScript::Initialize()
{
    BuiltinTypes::Initialize(&m_impl->globalCompilationUnit);

    /*if (Result res = InitializeHypScriptLib(*this); res.HasError())
    {
        HYP_LOG(HypScript, Error, "Failed to initialize HypScript lib! {}", res.GetError().GetMessage());
    }

    HYP_BREAKPOINT;*/
}

void HypScript::DestroyScript(Script_Instance* instance)
{
    if (!instance)
    {
        return;
    }

    delete instance;
}

Script_Instance* HypScript::Compile(SourceFile& sourceFile, ErrorList& outErrorList)
{
    if (!sourceFile.IsValid())
    {
        return nullptr;
    }

    SourceStream sourceStream(&sourceFile);
    TokenStream tokenStream(TokenStreamInfo { sourceFile.GetFilePath() });

    CompilationUnit compilationUnit;

    const FilePath basePath = sourceFile.GetFilePath().BasePath();

    // allow resolution of local modules
    compilationUnit.GetGlobalModule()->AddScanPath(basePath);
    // add local path as well
    compilationUnit.GetGlobalModule()->AddScanPath(CoreApi_GetExecutablePath());

    BuiltinTypes::RegisterTypes(&compilationUnit);

    Lexer lex(sourceStream, &tokenStream, &compilationUnit);
    lex.Analyze();

    AstIterator astIterator;
    SemanticAnalyzer semanticAnalyzer(&astIterator, &compilationUnit);

    Parser parser(&astIterator, &tokenStream, &compilationUnit);
    parser.Parse();

    astIterator.ResetPosition();
    semanticAnalyzer.Analyze();

#ifdef HYP_PRINT_AST
    AstPrintVisitor printer(&astIterator, &compilationUnit);
    printer.SetUseColors(true);
    printer.SetShowDetails(true);
    printer.SetShowLocations(true);
    printer.SetShowTypes(true);

    astIterator.ResetPosition();
    HYP_LOG(HypScript, Info, "{}", printer.PrintTree(astIterator.Peek()));
#endif

    outErrorList = compilationUnit.GetErrorList();
    outErrorList.WriteOutput(std::cout);

    if (!outErrorList.HasFatalErrors())
    {
        // only optimize if there were no errors
        // before this point
        astIterator.ResetPosition();

        Optimizer optimizer(&astIterator, &compilationUnit);
        optimizer.Optimize();

        // compile into bytecode instructions
        astIterator.ResetPosition();

        Compiler compiler(&astIterator, &compilationUnit);
        BytecodeChunk bytecodeChunk;

        if (auto compileResult = compiler.Compile())
        {
            bytecodeChunk.Append(std::move(compileResult));
        }
        else
        {
            return nullptr;
        }

        BuildParams buildParams {};

        CodeGenerator codeGenerator(buildParams);
        codeGenerator.Visit(&bytecodeChunk);
        codeGenerator.Bake();

        Script_Instance* scriptInstance = new Script_Instance {
            Script_Stream(codeGenerator.GetInternalByteStream().GetData())
        };

        return scriptInstance;
    }

    return nullptr;
}

InstructionStream* HypScript::Decompile(Script_Instance* instance, std::ostream* os) const
{
    if (!instance)
    {
        return nullptr;
    }

    return DecompilationUnit().Decompile(instance->stream, os);
}

void HypScript::Run(Script_Instance* instance)
{
    if (!instance)
    {
        return;
    }

    m_impl->vm->Execute(instance);
}

HypData HypScript::CallFunctionArgV(Script_Instance* instance, const HypData& value, HypData* args, ArgCount numArgs)
{
    Assert(instance != nullptr);
    Assert(IsFunction(value));

    if (numArgs != 0)
    {
        Assert(args != nullptr);

        for (ArgCount i = 0; i < numArgs; i++)
        {
            instance->thread.m_stack.Push(std::move(args[i]));
        }
    }

    // Create a reference since we know the lifetime of the function handle will exist longer than the call
    // and we don't want to move the underlying value
    Script_VMData vmData;
    vmData.type = Script_VMData::VALUE_REF;
    vmData.valueRef = const_cast<HypData*>(&value);

    m_impl->vm->InvokeNow(instance, ScriptApi_MakeValue(vmData), numArgs);

    if (numArgs != 0)
    {
        instance->thread.m_stack.Pop(numArgs);
    }

    return std::move(instance->thread.GetRegisters()[0]);
}

void HypScript::ReadLastReturnValue(Script_Instance* instance, HypData& outValue)
{
    Assert(instance != nullptr);

    outValue = ScriptApi_ShallowCopy(instance->thread.m_regs[0], m_impl->vm->GetGC());
}

bool HypScript::GetMember(Script_Instance* instance, const HypData& targetValue, const char* memberName, HypData& outValue)
{
    outValue = HypData();

    if (!targetValue.IsValid())
    {
        return false;
    }

    const AnyHandle& object = ScriptApi_GetObject(targetValue);

    if (!object)
    {
        return false;
    }

    const Class* cls = object.ptr->InstanceClass();
    Assert(cls != nullptr);

    IHypMember* member = cls->GetMember(WeakName(memberName));

    if (!member)
    {
        return false;
    }

    if (member->GetMemberType() == HypMemberType::TYPE_FIELD)
    {
        Field* field = static_cast<Field*>(member);

        outValue = ScriptApi_MakeValue(field->Get(targetValue));

        return true;
    }

    if (member->GetMemberType() == HypMemberType::TYPE_METHOD)
    {
        HypMethod* method = static_cast<HypMethod*>(member);

        Script_VMData vmData;

        if (method->IsScriptFunction())
        {
            Assert(method->GetParameters().Size() <= UINT8_MAX);

            vmData.type = Script_VMData::FUNCTION;
            vmData.func.m_addr = method->GetScriptAddress();
            vmData.func.m_nargs = (uint8)method->GetParameters().Size();
            vmData.func.m_flags = (uint8)method->GetFlags();
        }
        else
        {
            vmData.type = Script_VMData::NATIVE_FUNCTION;
            vmData.nativeFunc = method;
        }

        outValue = ScriptApi_MakeValue(vmData);

        return true;
    }

    return false;
}

bool HypScript::SetField(HypData& targetValue, const char* memberName, HypData&& value)
{
    if (!targetValue.IsValid())
    {
        return false;
    }

    const AnyHandle& object = ScriptApi_GetObject(targetValue);

    if (!object)
    {
        return false;
    }

    const Class* cls = object.ptr->InstanceClass();
    Assert(cls != nullptr);

    Field* field = cls->GetField(WeakName(memberName));

    if (!field)
    {
        return false;
    }

    field->Set(targetValue, std::move(value));

    return true;
}

bool HypScript::GetFunctionHandle(Script_Instance* instance, const char* name, HypData& outValue)
{
    outValue = HypData();

    HypData* pValue;
    if (!instance->exportedSymbols.Find(HashCode::GetHashCode(name).Value(), pValue))
    {
        return false;
    }

    if (!IsFunction(*pValue))
    {
        return false;
    }

    outValue = *pValue;

    return true;
}

bool HypScript::GetExportedValue(Script_Instance* instance, const char* name, HypData& outValue, bool getReference)
{
    outValue = HypData();

    HypData* pValue;
    if (!instance->exportedSymbols.Find(HashCode::GetHashCode(name).Value(), pValue))
    {
        return false;
    }

    Assert(pValue != nullptr);
    pValue = Deref(*pValue);

    if (getReference || ScriptApi_ShouldValuePassByRef(*pValue))
    {
        outValue = ScriptApi_MakeRef(pValue);

        return true;
    }

    outValue = *pValue;

    return true;
}

Script_SymbolTable& HypScript::GetExportedSymbols(Script_Instance* instance) const
{
    return instance->exportedSymbols;
}

} // namespace hyperion
