#ifndef GLIMMER_CONSTANTS_HLSLI
#define GLIMMER_CONSTANTS_HLSLI

/////////////SWRT/////////////

#define GLIMMER_PROBE_INSIDE_FRACTION 0.25
#define GLIMMER_PROBE_OUTSIDE_FRACTION 0.05

#define GLIMMER_PROBE_MIN_CLEARANCE 0.1
#define GLIMMER_PROBE_FREE_STEP 0.25
#define GLIMMER_PROBE_SETTLE_UPDATES 4u
#define GLIMMER_PROBE_INSIDE_STREAK 3u

#define GLIMMER_PROBE_RETURN_CLEARANCE 0.25
#define GLIMMER_PROBE_RETURN_STEP 0.01

#define GLIMMER_PROBE_NOISE_RATE 0.25
#define GLIMMER_PROBE_DRIFT_RATE 0.0625
#define GLIMMER_PROBE_SPREAD_RATE 0.0625
#define GLIMMER_PROBE_DRIFT_NOISE (6.0 * GLIMMER_PROBE_DRIFT_RATE / (2.0 - GLIMMER_PROBE_DRIFT_RATE))

#define GLIMMER_PROBE_DRIFT_STEP_UP 2.0
#define GLIMMER_PROBE_DRIFT_STEP_DOWN 4.0
#define GLIMMER_PROBE_MIN_RELATIVE_SIGMA 0.05

// how far past the drift's own noise a probe's light has to move before the rest of its block wakes with it
#define GLIMMER_PROBE_WAKE_BLOCK_BIAS 1.0

#define GLIMMER_PROBE_FIREFLY_SIGMAS 3.0
#define GLIMMER_PROBE_FIREFLY_MIN_HISTORY 4.0

#define GLIMMER_PROBE_VISIBILITY_SHARPNESS 12.0

#define GLIMMER_PROBE_MAX_HISTORY 256.0
#define GLIMMER_PROBE_MAX_RAYS 32

///////////////////////////////

#define GLIMMER_SH_CASCADES 5
#define GLIMMER_SH_GRID_XZ 32
#define GLIMMER_SH_GRID_Y 16

#define GLIMMER_SH_DEPTH_RANGE 2.0
#define GLIMMER_SH_MAX_ORIGIN_OFFSET 0.5

#define GLIMMER_SH_AXIS_DEPTHS 6

/////////////SH///////////////

#endif