[DeferredIndirect]
versions = SSGI_ENABLED, RT_REFLECTIONS, RT_GI, HBIL_ENABLED, HBAO_EABLED
PS = DeferredIndirect.hlsl
VS = DeferredIndirect.hlsl

[DeferredDirect]
versions = LIGHT_TYPE(DIRECTIONAL POINT SPOT AREA_RECT)
PS = DeferredDirect.hlsl
VS = DeferredDirect.hlsl

[ApplyReflectionProbe]
versions = ENV_PROBE_PARALLAX_CORRECTED
PS = deferred/ApplyReflectionProbe.hlsl
VS = deferred/ApplyReflectionProbe.hlsl

[ApplyLightmap]
PS = deferred/ApplyLightmap.hlsl
VS = deferred/ApplyLightmap.hlsl

[ApplyFogVolume]
PS = deferred/ApplyFogVolume.hlsl
VS = deferred/ApplyFogVolume.hlsl

[Tonemap]
versions = OUTPUT(PQ_HDR SDR)
PS = Tonemap.hlsl
VS = Tonemap.hlsl

[FXAA]
PS = FXAA.hlsl
VS = FXAA.hlsl

[DOFBlurDirection]
versions = DIRECTION(HORIZONTAL VERTICAL)
PS = _old/dof/DOFBlurDirection.frag
VS = PostEffect.vert

[DOFBlurMix]
PS = _old/dof/DOFBlurMix.frag
VS = PostEffect.vert

[ComputeVisibility]
versions = INSTANCING
CS = OcclusionCulling/ComputeVisibility.hlsl

[GenerateDepthPyramid]
CS = OcclusionCulling/GenerateDepthPyramid.hlsl

[GenerateMipmaps]
VS = PostEffect.vert
PS = GenerateMipmaps.frag

[BlitTexture]
versions = HALFRES
PS = BlitTexture.hlsl
VS = BlitTexture.hlsl

[MergeHalfResTextures]
PS = MergeHalfResTextures.hlsl
VS = MergeHalfResTextures.hlsl

[DrawCubemap]
versions = HAS_ALBEDO_MAP, MODE_SHADOWS, WRITE_NORMALS, WRITE_MOMENTS, INSTANCING, ENV_PROBE, SKINNING
PS = DrawCubemap.hlsl
VS = DrawCubemap.hlsl

[RenderSky]
PS = sky/RenderSky.frag
VS = sky/RenderSky.vert

[ComputeSH]
versions = MODE(CLEAR BUILD_COEFFICIENTS REDUCE FINALIZE), LIGHTING
CS = env_probe/ComputeSH.hlsl

[ConvolveProbe]
versions = NUM_SAMPLES(16 32 64 128), LOBE_SIZE(0.9 0.94 0.98)
CS = env_probe/ConvolveProbe.hlsl

[GeometryPass]
versions = SKINNING, ALPHA_DISCARD, INSTANCING, SHADING_TYPE(DEFERRED FORWARD UNLIT LIGHTMAPPED), HAS_ALBEDO_MAP, HAS_NORMAL_MAP, HAS_PARALLAX_MAP, HAS_METALNESS_MAP, HAS_ROUGHNESS_MAP, HAS_AO_MAP
PS = GeometryPass.hlsl
VS = DefaultVertex.hlsl

[Skybox]
versions = INSTANCING
PS = Skybox.hlsl
VS = Skybox.hlsl

[Terrain]
versions = INSTANCING
PS = Terrain.frag
VS = DefaultVertex.hlsl

[HBAO]
versions = HBIL_ENABLED, HALFRES
PS = hbao/HBAO.frag
VS = PostEffect.vert

[Particle]
PS = particles/Particle.hlsl
VS = particles/Particle.hlsl

[UpdateParticles]
versions = HAS_PHYSICS
CS = particles/UpdateParticles.hlsl

[DrawShadowMap]
versions = MODE(STANDARD VSM PCF CONTACT_HARDENED), INSTANCING, SKINNING, ALPHA_DISCARD
PS = DrawShadowMap.hlsl
VS = DrawShadowMap.hlsl

[BlurShadowMap]
CS = shadow/BlurShadowMap.comp

[CombineShadowMaps]
versions = VSM
PS = shadow/CombineShadowMaps.frag
VS = PostEffect.vert

[SSRWriteUVs]
versions = CONE_TRACING, ROUGHNESS_SCATTERING
VS = ssr/SSRWriteUVs.hlsl
PS = ssr/SSRWriteUVs.hlsl

[SSRSampleGBuffer]
versions = CONE_TRACING
VS = ssr/SSRSampleGBuffer.hlsl
PS = ssr/SSRSampleGBuffer.hlsl

[SSGI]
versions = OUTPUT(RGBA8 RGBA16F RGBA32F)
CS = ssr/SSGI.hlsl

[UIObject]
versions = TEXTURED, UI_TEXT
PS = ui/UIObject.hlsl
VS = ui/UIObject.hlsl

[DebugVis]
versions = IMMEDIATE_MODE, INSTANCING
PS = DebugVis.hlsl
VS = DebugVis.hlsl

# RT

[RayTracedReflections]
versions = HAS_ENV_PROBE
RayGen = rt/reflections/RayTracedReflections.hlsl
ClosestHit = rt/reflections/RayTracedReflections.rchit.hlsl
Miss = rt/reflections/RayTracedReflections.rmiss.hlsl

[PathTracer]
RayGen = rt/pathtracer/PathTracer.hlsl
ClosestHit = rt/pathtracer/PathTracer.rchit.hlsl
Miss = rt/pathtracer/PathTracer.rmiss.hlsl

[LightmapPathTracer]
versions = MODE(IRRADIANCE RADIANCE FULL)
RayGen = rt/lightmapper/LightmapPathTracer.hlsl
ClosestHit = rt/lightmapper/LightmapPathTracer.rchit.hlsl
Miss = rt/lightmapper/LightmapPathTracer.rmiss.hlsl

[DDGI]
versions = HAS_ENV_PROBE
RayGen = rt/gi/DDGI.hlsl
ClosestHit = rt/gi/DDGI.rchit.hlsl
Miss = rt/gi/DDGI.rmiss.hlsl

[RTCopyBorderTexelsIrradiance]
CS = rt/copy_border_texels_irradiance.comp

[RTCopyBorderTexelsDepth]
CS = rt/copy_border_texels_depth.comp

[RTProbeUpdateIrradiance]
CS = rt/probe_update_irradiance.comp

[RTProbeUpdateDepth]
CS = rt/probe_update_depth.comp

# Temporal

[TemporalAA]
CS = TAA.hlsl

[TemporalBlending]
versions = OUTPUT(RGBA8 RGBA16F RGBA32F), TEMPORAL_BLEND_TECHNIQUE(0 1 2 3 4)
CS = TemporalBlending.hlsl

[ImageBlurCompute]
versions = HORIZONTAL, OUTPUT(RGBA8 RGBA16F RGBA32F)
CS = Blur.comp

# Lightmapping
[DilateLightmap]
CS = lightmapping/DilateLightmap.comp.glsl

# Third Party Shaders

[FfxParallelSort_Reduce]
entry_point = FfxParallelSortReduce
CS = third_party/FfxParallelSort.hlsl

[FfxParallelSort_ScanAdd]
entry_point = FfxParallelSortScanAdd
CS = third_party/FfxParallelSort.hlsl

[FfxParallelSort_Scan]
entry_point = FfxParallelSortScan
CS = third_party/FfxParallelSort.hlsl

[FfxParallelSort_Scatter]
entry_point = FfxParallelSortScatter
CS = third_party/FfxParallelSort.hlsl

[FfxParallelSort_Count]
entry_point = FfxParallelSortCount
CS = third_party/FfxParallelSort.hlsl

# Testing

[TestHLSL]
VS = TestHLSL.hlsl