[Fallback]
PS = Fallback.hlsl
VS = Fallback.hlsl

[DeferredIndirect]
PS = DeferredIndirect.hlsl
VS = DeferredIndirect.hlsl

[DeferredDirect]
PS = DeferredDirect.hlsl
VS = DeferredDirect.hlsl

[ApplyReflectionProbe]
versions = ENV_PROBE_PARALLAX_CORRECTED
PS = deferred/ApplyReflectionProbe.hlsl
VS = deferred/ApplyReflectionProbe.hlsl

[ApplyLightmap]
PS = deferred/ApplyLightmap.hlsl
VS = deferred/ApplyLightmap.hlsl

[ApplyFogVolume]
PS = deferred/ApplyFogVolume.hlsl
VS = deferred/ApplyFogVolume.hlsl

[Sprite]
PS = sprite/Sprite.hlsl
VS = sprite/Sprite.hlsl

[Tonemap]
versions = OUTPUT(PQ_HDR SDR)
PS = Tonemap.hlsl
VS = Tonemap.hlsl

[BloomExtract]
CS = bloom/BloomExtract.hlsl

[BloomBlur]
PS = bloom/BloomBlur.hlsl
VS = bloom/BloomBlur.hlsl

[BloomUpsample]
PS = bloom/BloomUpsample.hlsl
VS = bloom/BloomUpsample.hlsl

[BloomDownsample]
PS = bloom/BloomDownsample.hlsl
VS = bloom/BloomDownsample.hlsl

[FXAA]
PS = FXAA.hlsl
VS = FXAA.hlsl

[ComputeVisibility]
versions = INSTANCING
CS = OcclusionCulling/ComputeVisibility.hlsl

[GenerateDepthPyramid]
CS = OcclusionCulling/GenerateDepthPyramid.hlsl

[BlitTexture]
PS = BlitTexture.hlsl
VS = BlitTexture.hlsl

[MergeCheckerboard]
PS = MergeCheckerboard.hlsl
VS = MergeCheckerboard.hlsl

[DrawCubemap]
PS = DrawCubemap.hlsl
VS = DrawCubemap.hlsl

[RenderSky]
PS = sky/RenderSky.hlsl
VS = sky/RenderSky.hlsl

[ComputeSH]
CS = env_probe/ComputeSH.hlsl

[ConvolveProbe]
CS = env_probe/ConvolveProbe.hlsl

[GeometryPass]
PS = GeometryPass.hlsl
VS = DefaultVertex.hlsl

[Skybox]
versions = INSTANCING
PS = Skybox.hlsl
VS = Skybox.hlsl

[Terrain]
versions = INSTANCING
PS = Terrain.hlsl
VS = DefaultVertex.hlsl

[HBAO]
PS = hbao/HBAO.hlsl
VS = hbao/HBAO.hlsl

[Particle]
PS = particles/Particle.hlsl
VS = particles/Particle.hlsl

[UpdateParticles]
versions = HAS_PHYSICS
CS = particles/UpdateParticles.hlsl

[DrawShadowMap]
PS = DrawShadowMap.hlsl
VS = DrawShadowMap.hlsl

[SSRWriteUVs]
VS = ssr/SSRWriteUVs.hlsl
PS = ssr/SSRWriteUVs.hlsl

[SSRSampleGBuffer]
VS = ssr/SSRSampleGBuffer.hlsl
PS = ssr/SSRSampleGBuffer.hlsl

[SSGI]
versions = OUTPUT(RGBA8 RGBA16F RGBA32F)
CS = ssr/SSGI.hlsl

[SSGIUpsample]
VS = ssr/SSGIUpsample.hlsl
PS = ssr/SSGIUpsample.hlsl

[UIObject]
PS = ui/UIObject.hlsl
VS = ui/UIObject.hlsl

[DebugVis]
PS = DebugVis.hlsl
VS = DebugVis.hlsl

# RT

[RayTracedReflections]
versions = HAS_ENV_PROBE
RayGen = rt/reflections/RayTracedReflections.hlsl
ClosestHit = rt/reflections/RayTracedReflections.rchit.hlsl
Miss = rt/reflections/RayTracedReflections.rmiss.hlsl

[PathTracer]
RayGen = rt/pathtracer/PathTracer.hlsl
ClosestHit = rt/pathtracer/PathTracer.rchit.hlsl
Miss = rt/pathtracer/PathTracer.rmiss.hlsl

[LightmapPathTracer]
RayGen = rt/lightmapper/LightmapPathTracer.hlsl
ClosestHit = rt/lightmapper/LightmapPathTracer.rchit.hlsl
Miss = rt/lightmapper/LightmapPathTracer.rmiss.hlsl

[DDGI]
RayGen = rt/gi/DDGI.hlsl
ClosestHit = rt/gi/DDGI.rchit.hlsl
Miss = rt/gi/DDGI.rmiss.hlsl

[RTCopyBorderTexelsIrradiance]
CS = rt/copy_border_texels_irradiance.comp

[RTCopyBorderTexelsDepth]
CS = rt/copy_border_texels_depth.comp

[UpdateProbeData]
CS = rt/gi/UpdateProbeData.hlsl

# Temporal

[TAA]
CS = TAA.hlsl

[TemporalBlending]
CS = TemporalBlending.hlsl
