//! Raw bindings to the Hyperion engine.
//!
//! Two layers: a handful of `Hyp_*` functions linked directly from the engine library (lifecycle, reference
//! counting, the binding lookup), and [`Bindings`], a table of every reflected engine method, generated by the
//! engine's CodeGen and resolved by name at startup through `Hyp_ResolveBinding`.
//!
//! Conventions of the generated functions:
//! - Engine objects are opaque and passed as `*mut T`. A returned object is borrowed unless the engine's
//!   `Bindings.json` marks the return `handle_retained`, in which case the caller owns a reference and must
//!   `Hyp_Release` it.
//! - Structs are passed by pointer and returned through a trailing out-pointer.
//! - Strings go in as NUL-terminated C strings and come back as a [`HypString`] the caller frees with `Hyp_Free`.

#![allow(non_snake_case, non_camel_case_types, non_upper_case_globals)]

use core::ffi::{c_char, c_int, c_void};
use std::sync::OnceLock;

/// An engine-allocated array returned through an out-pointer. Free `data` with [`Hyp_Free`].
#[repr(C)]
pub struct HypArray<T> {
    pub data: *mut T,
    pub length: u32,
    pub cap: u32,
}

impl<T> HypArray<T> {
    pub const fn empty() -> Self {
        Self { data: core::ptr::null_mut(), length: 0, cap: 0 }
    }
}

pub type HypString = HypArray<c_char>;

// Value types with the same layout as the engine's.

#[repr(C, align(8))]
#[derive(Clone, Copy, Debug, Default, PartialEq)]
pub struct Vec2f {
    pub x: f32,
    pub y: f32,
}

#[repr(C, align(16))]
#[derive(Clone, Copy, Debug, Default, PartialEq)]
pub struct Vec3f {
    pub x: f32,
    pub y: f32,
    pub z: f32,
}

#[repr(C, align(16))]
#[derive(Clone, Copy, Debug, Default, PartialEq)]
pub struct Vec4f {
    pub x: f32,
    pub y: f32,
    pub z: f32,
    pub w: f32,
}

#[repr(C, align(8))]
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq)]
pub struct Vec2i {
    pub x: i32,
    pub y: i32,
}

#[repr(C, align(8))]
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq)]
pub struct Vec2u {
    pub x: u32,
    pub y: u32,
}

#[repr(C)]
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq, Hash)]
pub struct Name {
    pub hash: u64,
}

/// The hash of a name the engine looks things up by. Same value as the [`Name`] of that string.
#[repr(C)]
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq, Hash)]
pub struct StringHash {
    pub hash: u64,
}

impl From<Name> for StringHash {
    fn from(name: Name) -> Self {
        Self { hash: name.hash }
    }
}

#[repr(C)]
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq)]
pub struct Color {
    pub value: u32,
}

const _: () = {
    assert!(core::mem::size_of::<Vec2f>() == 8);
    assert!(core::mem::size_of::<Vec3f>() == 16);
    assert!(core::mem::size_of::<Vec4f>() == 16);
    assert!(core::mem::size_of::<Vec2i>() == 8);
    assert!(core::mem::size_of::<Vec2u>() == 8);
    assert!(core::mem::size_of::<Name>() == 8);
    assert!(core::mem::size_of::<StringHash>() == 8);
    assert!(core::mem::size_of::<Color>() == 4);
};

include!(concat!(env!("CARGO_MANIFEST_DIR"), "/../../Generated/Rust/bindings.rs"));

/// Hooks for a game driven through `Hyp_CreateCallbackGame`. Each is optional and runs on the engine's sim thread.
#[repr(C)]
pub struct HypGameCallbacks {
    pub on_launch: Option<unsafe extern "C" fn(user_data: *mut c_void, game: *mut Game)>,
    pub on_update: Option<unsafe extern "C" fn(user_data: *mut c_void, game: *mut Game, delta: f32)>,
    pub on_shutdown: Option<unsafe extern "C" fn(user_data: *mut c_void, game: *mut Game)>,
}

pub const HYP_LOG_ERROR: c_int = 1;
pub const HYP_LOG_WARNING: c_int = 2;
pub const HYP_LOG_INFO: c_int = 3;

// raw-dylib: no import library needed, so this links the same way with the MSVC and GNU toolchains
#[cfg_attr(windows, link(name = "hyperion", kind = "raw-dylib"))]
#[cfg_attr(not(windows), link(name = "hyperion"))]
unsafe extern "C" {
    pub fn Hyp_Initialize(argc: c_int, argv: *mut *mut c_char) -> c_int;
    pub fn Hyp_Shutdown();
    pub fn Hyp_LaunchThreads() -> c_int;
    pub fn Hyp_RequestQuit();

    pub fn Hyp_SetGame(game: *mut Game);
    pub fn Hyp_DestroyGame(game: *mut Game);
    pub fn Hyp_CreateCallbackGame(callbacks: *const HypGameCallbacks, user_data: *mut c_void) -> *mut Game;

    pub fn Hyp_ResolveBinding(name: *const c_char) -> *mut c_void;
    pub fn Hyp_GetBindingAbiVersion() -> c_int;

    pub fn Hyp_Retain(object: *mut c_void);
    pub fn Hyp_Release(object: *mut c_void);
    pub fn Hyp_Free(data: *mut c_void);

    pub fn Hyp_Log(level: c_int, message: *const c_char);
    pub fn Hyp_GetEngineVersion(major: *mut u32, minor: *mut u32, patch: *mut u32);

    pub fn Name_FromString(string: *const c_char, weak: bool, out_name: *mut Name);
}

static BINDINGS: OnceLock<Bindings> = OnceLock::new();

/// The generated binding table, resolved against the loaded engine on first use.
pub fn bindings() -> &'static Bindings {
    BINDINGS.get_or_init(|| unsafe { Bindings::load(Hyp_ResolveBinding) })
}

/// Whether the loaded engine speaks the binding ABI this crate was generated for.
pub fn is_binding_abi_compatible() -> bool {
    unsafe { Hyp_GetBindingAbiVersion() == BINDING_ABI_VERSION }
}
