
#version 450

#extension GL_GOOGLE_include_directive : require

#define WORKGROUP_SIZE 8

layout(local_size_x = WORKGROUP_SIZE, local_size_y = WORKGROUP_SIZE) in;

#define HYP_DO_NOT_DEFINE_DESCRIPTOR_SETS

#define HYP_SAMPLER_NEAREST sampler_nearest
#define HYP_SAMPLER_LINEAR sampler_linear

#include "../include/defines.inc"
#include "../include/shared.inc"
#include "../include/noise.inc"
#include "../include/packing.inc"
#include "../include/scene.inc"
#include "../include/brdf.inc"

#undef HYP_DO_NOT_DEFINE_DESCRIPTOR_SETS

#include "../include/env_probe.inc"

HYP_DESCRIPTOR_SRV_DYNAMIC(ConvolveProbeDescriptorSet, CurrentEnvProbe) readonly buffer CurrentEnvProbe
{
    EnvProbe current_env_probe;
};

HYP_DESCRIPTOR_BUFFER(ConvolveProbeDescriptorSet, SphereSamplesBuffer) uniform SphereSamplesBuffer
{
    vec4 sphere_samples[4096];
};

HYP_DESCRIPTOR_SRV(ConvolveProbeDescriptorSet, ColorTexture) uniform textureCube color_texture;

HYP_DESCRIPTOR_SAMPLER(ConvolveProbeDescriptorSet, SamplerLinear) uniform sampler sampler_linear;
HYP_DESCRIPTOR_SAMPLER(ConvolveProbeDescriptorSet, SamplerNearest) uniform sampler sampler_nearest;

HYP_DESCRIPTOR_UAV(ConvolveProbeDescriptorSet, OutImage, format = rgba8) uniform imageCube out_image;

HYP_DESCRIPTOR_BUFFER(ConvolveProbeDescriptorSet, UniformBuffer) uniform UniformBuffer
{
    uvec2 out_image_dimensions;
    uvec2 in_image_dimensions;
    vec4 world_position;
};

vec4 ConvolveProbe(uvec2 local_coord)
{
#if NUM_SAMPLES <= 0
    return vec4(0.0);
#endif

    const int num_samples = NUM_SAMPLES;
    const float lobe_size = LOBE_SIZE;

    uint face = gl_GlobalInvocationID.z;

    const vec3 dir = normalize(GetCubemapCoord(face, (vec2(local_coord) + 0.5) / vec2(out_image_dimensions)));

    vec4 sum_radiance = vec4(0.0);

    uint seed = uint(gl_GlobalInvocationID.x) * uint(gl_GlobalInvocationID.y);

    for (int i = 0; i < num_samples; i++)
    {
        vec3 offset = sphere_samples[i % 4096].xyz;
        vec3 sample_dir = normalize(dir + vec3(lobe_size) * offset);

        vec4 color = SAMPLE_TEXTURE_CUBE(sampler_linear, color_texture, sample_dir);

        sum_radiance += color;
    }

    sum_radiance /= float(num_samples);

    return sum_radiance;
}

void main(void)
{
    if (any(greaterThanEqual(gl_GlobalInvocationID.xy, out_image_dimensions)))
    {
        return;
    }

    const uvec2 coord = gl_GlobalInvocationID.xy;
    vec2 uv = (vec2(coord) + 0.5) / vec2(out_image_dimensions);

    vec4 color = ConvolveProbe(coord);

    imageStore(out_image, ivec3(coord, int(gl_GlobalInvocationID.z)), color);
}