DECLARE_GFX_TYPE(Device);
DECLARE_GFX_TYPE(Swapchain);
DECLARE_GFX_TYPE(GpuImage);
DECLARE_GFX_TYPE(GpuImageView);
DECLARE_GFX_TYPE(Sampler);
DECLARE_GFX_TYPE(GpuBuffer);
DECLARE_GFX_TYPE(Frame);
DECLARE_GFX_TYPE(Framebuffer);
DECLARE_GFX_TYPE(CommandBuffer);
DECLARE_GFX_TYPE(Attachment);
DECLARE_GFX_TYPE(ComputePipeline);
DECLARE_GFX_TYPE(GraphicsPipeline);
DECLARE_GFX_TYPE(RaytracingPipeline);
DECLARE_GFX_TYPE(Shader);
DECLARE_GFX_TYPE(DescriptorSet);
DECLARE_GFX_TYPE(DescriptorTable);
DECLARE_GFX_TYPE(GpuBlas);
DECLARE_GFX_TYPE(GpuTlas);
DECLARE_GFX_TYPE(TextureViewCache);

#if HYP_VULKAN
DECLARE_VULKAN_GFX_TYPE(Semaphore);
DECLARE_VULKAN_GFX_TYPE(Fence);
DECLARE_VULKAN_GFX_TYPE(RenderPass);
#elif HYP_DX12
DECLARE_DX12_GFX_TYPE(Fence);
DECLARE_DX12_GFX_TYPE(RaytracingPipeline);
DECLARE_DX12_GFX_TYPE(GpuBlas);
DECLARE_DX12_GFX_TYPE(GpuTlas);
#endif