/* Copyright (c) 2024 No Tomorrow Games. All rights reserved. */

#include <util/ParseUtil.hpp>

#include <core/Defines.hpp>

#include <core/utilities/Format.hpp>

#include <regex>
#include <string>
#include <sstream>

namespace hyperion {
namespace buildtool {

Optional<String> ExtractCXXClassName(const String& line)
{
    static const std::regex s_pattern(
        "(?:class|struct|(?:enum class)|enum)\\s+(?:alignas\\(.*\\)\\s+)?(?:HYP_API\\s+)?(\\w+)");

    std::string str = line.Data();
    std::smatch match;

    if (std::regex_search(str, match, s_pattern))
    {
        return match[1].str().c_str();
    }

    return {};
}

Array<String> ExtractCXXBaseClasses(const String& line)
{
    static const std::regex s_pattern(
        "((?:class|struct|(?:enum class)|enum)\\s+(?:alignas\\(.*\\)\\s+)?(?:HYP_API\\s+)?(?:\\w+)\\s*(?:final)?\\s*:\\s*((?:public|private|protected)?\\s*(?:\\w+\\s*,?\\s*)+))");

    Array<String> results;

    std::string str = line.Data();
    std::smatch match;

    if (std::regex_search(str, match, s_pattern))
    {
        std::string baseClasses = match[1].str();
        std::stringstream ss(baseClasses);
        std::string part;

        while (std::getline(ss, part, ','))
        {
            std::stringstream s2(part);
            std::string token, last;

            while (s2 >> token)
            {
                last = token;
            }

            if (!last.empty())
            {
                results.PushBack(last.c_str());
            }
        }
    }
    return results;
}

bool IsCXXClassDecl(const String& line)
{
    static const std::regex s_pattern(
        "(?:class)\\s+(?:alignas\\(.*\\)\\s+)?(?:HYP_API\\s+)?(\\w+)");

    std::string str = line.Data();
    std::smatch match;

    return std::regex_search(str, match, s_pattern);
}

bool IsCXXStructDecl(const String& line)
{
    static const std::regex s_pattern(
        "(?:struct)\\s+(?:alignas\\(.*\\)\\s+)?(?:HYP_API\\s+)?(\\w+)");

    std::string str = line.Data();
    std::smatch match;

    return std::regex_search(str, match, s_pattern);
}

bool IsCXXEnumDecl(const String& line)
{
    static const std::regex s_pattern(
        "(?:enum|(?:enum class))\\s+(\\w+)");

    std::string str = line.Data();
    std::smatch match;

    return std::regex_search(str, match, s_pattern);
}

bool IsCXXEnumClassDecl(const String& line)
{
    static const std::regex s_pattern(
        "(?:enum class)\\s+(\\w+)");

    std::string str = line.Data();
    std::smatch match;

    return std::regex_search(str, match, s_pattern);
}

String GetDateTimeString()
{
    char buf[80];
#ifdef HYP_UNIX
    time_t now = time(nullptr);
    struct tm tstruct;
    localtime_r(&now, &tstruct);
    strftime(buf, sizeof(buf), "%Y-%m-%d %X", &tstruct);

#elif defined(HYP_WINDOWS)
    std::time_t now = std::time(nullptr);
    std::tm tstruct;
    localtime_s(&tstruct, &now);
    std::strftime(buf, sizeof(buf), "%Y-%m-%d %X", &tstruct);
#else
#error Platform not supported
#endif

    return String(buf);
}

String GetGeneratedFilePreamble(const String& srcPath)
{
    // replace slashes with portable '/' to reduce diffs
    return HYP_FORMAT("/* Auto-generated by HypBuildTool v{}.{}.{}. Do not modify this file directly.\n"
                      " * Source: {}\n"
                      " */\n\n",
        HYP_BUILD_TOOL_VERSION_MAJOR,
        HYP_BUILD_TOOL_VERSION_MINOR,
        HYP_BUILD_TOOL_VERSION_PATCH,
        srcPath.Length() ? srcPath.ReplaceAll("\\", "/") : "<no source file>");
}

} // namespace buildtool
} // namespace hyperion