#include <script/HypScript.hpp>

#include <script/vm/BytecodeStream.hpp>

#include <script/compiler/emit/BytecodeChunk.hpp>
#include <script/compiler/emit/InstructionStream.hpp>
#include <script/compiler/emit/Instruction.hpp>
#include <script/compiler/emit/codegen/CodeGenerator.hpp>

#include <script/compiler/Module.hpp>
#include <script/compiler/SemanticAnalyzer.hpp>
#include <script/compiler/Optimizer.hpp>
#include <script/compiler/Lexer.hpp>
#include <script/compiler/Parser.hpp>
#include <script/compiler/Compiler.hpp>

#include <script/compiler/dis/DecompilationUnit.hpp>

#include <script/compiler/AstPrintVisitor.hpp>

#include <script/vm/VirtualMachine.hpp>

#include <Core/reflection/Class.hpp>
#include <Core/reflection/Method.hpp>
#include <Core/reflection/Field.hpp>
#include <Core/reflection/Member.hpp>
#include <Core/reflection/ClassRegistry.hpp>

#include <Core/io/BufferedByteReader.hpp>

#include <Core/logging/Logger.hpp>
#include <Core/logging/LogChannels.hpp>

#include <Core/utilities/Format.hpp>
#include <Core/utilities/Result.hpp>

#include <iostream>

namespace Hyperion {

// #define HYP_PRINT_AST

HYP_DEFINE_LOG_CHANNEL(HypScript);

static constexpr SizeType ScriptPoolBlockSize = 8 * 1024 * 1024;

static Pool s_scriptPoolInstance { ScriptPoolBlockSize };
Pool* g_scriptPool = &s_scriptPoolInstance;

#pragma region HypScriptImpl

struct HypScriptImpl
{
    CompilationUnit globalCompilationUnit;
    VirtualMachine* vm;
    ScriptInstance* globalInstance;

    HypScriptImpl()
        : vm(new VirtualMachine()),
          globalInstance(nullptr)
    {
    }

    HypScriptImpl(const HypScriptImpl& other) = delete;
    HypScriptImpl& operator=(const HypScriptImpl& other) = delete;

    ~HypScriptImpl()
    {
        if (globalInstance)
        {
            delete globalInstance;
            globalInstance = nullptr;
        }

        delete vm;
    }
};

#pragma endregion HypScriptImpl

/// Initialize the `Lib` script which is used to call into HypScript code from C++.
static Result InitializeHypScriptLib(HypScript& hs)
{
    // create the global script instance using Lib.hyp (generated by the CodeGen tool)
    static const FilePath s_libPath = CoreApi::GetExecutablePath() / "Lib.hyp";

    FileBufferedReaderSource source { s_libPath };
    BufferedByteReader reader { &source };

    if (!reader.IsOpen())
    {
        return HYP_MAKE_ERROR(Error, "Failed to open Lib.hyp at path '{}'! Did the build tool run correctly?", s_libPath);
    }

    ByteBuffer byteBuffer = reader.ReadBytes();

    SourceFile sourceFile(s_libPath, byteBuffer.Size());
    sourceFile.ReadIntoBuffer(byteBuffer);

    ErrorList errorList;

    ScriptInstance* instance = hs.Compile(sourceFile, errorList);

    if (errorList.HasFatalErrors())
    {
        return HYP_MAKE_ERROR(Error, "Failed to compile Lib.hyp! The script system will not function correctly.");
    }

    Assert(instance != nullptr);

    // run the main script to initialize classes, functions, etc.
    hs.Run(instance);

    return {};
}

HypScript& HypScript::GetInstance()
{
    static HypScript s_hypScriptInstance;

    return s_hypScriptInstance;
}

HypScript::HypScript()
    : m_impl(MakePimpl<HypScriptImpl>())
{
}

HypScript::~HypScript() = default;

VirtualMachine* HypScript::GetVM() const
{
    return m_impl->vm;
}

ScriptInstance* HypScript::GetGlobalInstance() const
{
    return m_impl->globalInstance;
}

void HypScript::Initialize()
{
    BuiltinTypes::Initialize(&m_impl->globalCompilationUnit);

    /*if (Result res = InitializeHypScriptLib(*this); res.HasError())
    {
        HYP_LOG(HypScript, Error, "Failed to initialize HypScript lib! {}", res.GetError().GetMessage());
    }

    HYP_BREAKPOINT;*/
}

void HypScript::DestroyScript(ScriptInstance* instance)
{
    if (!instance)
    {
        return;
    }

    delete instance;
}

ScriptInstance* HypScript::Compile(SourceFile& sourceFile, ErrorList& outErrorList)
{
    if (!sourceFile.IsValid())
    {
        return nullptr;
    }

    SourceStream sourceStream(&sourceFile);
    TokenStream tokenStream(TokenStreamInfo { sourceFile.GetFilePath() });

    CompilationUnit compilationUnit;

    const FilePath basePath = sourceFile.GetFilePath().BasePath();

    // allow resolution of local modules
    compilationUnit.GetGlobalModule()->AddScanPath(basePath);
    // add local path as well
    compilationUnit.GetGlobalModule()->AddScanPath(CoreApi::GetExecutablePath());

    BuiltinTypes::RegisterTypes(&compilationUnit);

    Lexer lex(sourceStream, &tokenStream, &compilationUnit);
    lex.Analyze();

    AstIterator astIterator;
    SemanticAnalyzer semanticAnalyzer(&astIterator, &compilationUnit);

    Parser parser(&astIterator, &tokenStream, &compilationUnit);
    parser.Parse();

    astIterator.ResetPosition();
    semanticAnalyzer.Analyze();

#ifdef HYP_PRINT_AST
    AstPrintVisitor printer(&astIterator, &compilationUnit);
    printer.SetUseColors(true);
    printer.SetShowDetails(true);
    printer.SetShowLocations(true);
    printer.SetShowTypes(true);

    astIterator.ResetPosition();
    HYP_LOG(HypScript, Info, "{}", printer.PrintTree(astIterator.Peek()));
#endif

    outErrorList = compilationUnit.GetErrorList();
    outErrorList.WriteOutput(std::cout);

    if (!outErrorList.HasFatalErrors())
    {
        // only optimize if there were no errors
        // before this point
        astIterator.ResetPosition();

        Optimizer optimizer(&astIterator, &compilationUnit);
        optimizer.Optimize();

        // compile into bytecode instructions
        astIterator.ResetPosition();

        Compiler compiler(&astIterator, &compilationUnit);
        BytecodeChunk bytecodeChunk;

        if (auto compileResult = compiler.Compile())
        {
            bytecodeChunk.Append(std::move(compileResult));
        }
        else
        {
            return nullptr;
        }

        BuildParams buildParams {};

        CodeGenerator codeGenerator(buildParams);
        codeGenerator.Visit(&bytecodeChunk);
        codeGenerator.Bake();

        ScriptInstance* scriptInstance = new ScriptInstance {
            BytecodeStream(codeGenerator.GetInternalByteStream().GetData())
        };

        return scriptInstance;
    }

    return nullptr;
}

InstructionStream* HypScript::Decompile(ScriptInstance* instance, std::ostream* os) const
{
    if (!instance)
    {
        return nullptr;
    }

    return DecompilationUnit().Decompile(instance->stream, os);
}

void HypScript::Run(ScriptInstance* instance)
{
    if (!instance)
    {
        return;
    }

    m_impl->vm->Execute(instance);
}

BoxedValue HypScript::CallFunctionArgV(ScriptInstance* instance, const BoxedValue& value, BoxedValue* args, ArgCount numArgs)
{
    Assert(instance != nullptr);
    Assert(IsFunction(value));

    if (numArgs != 0)
    {
        Assert(args != nullptr);

        for (ArgCount i = 0; i < numArgs; i++)
        {
            instance->thread.m_stack.Push(std::move(args[i]));
        }
    }

    // Create a reference since we know the lifetime of the function handle will exist longer than the call
    // and we don't want to move the underlying value
    ScriptObjectData data;
    data.type = ScriptObjectData::Type::Reference;
    data.valueRef = const_cast<BoxedValue*>(&value);

    m_impl->vm->InvokeNow(instance, MakeValue(data), numArgs);

    if (numArgs != 0)
    {
        instance->thread.m_stack.Pop(numArgs);
    }

    return std::move(instance->thread.GetRegisters()[0]);
}

void HypScript::ReadLastReturnValue(ScriptInstance* instance, BoxedValue& outValue)
{
    Assert(instance != nullptr);

    outValue = ShallowCopy(instance->thread.m_regs[0], m_impl->vm->GetGC());
}

bool HypScript::GetMember(ScriptInstance* instance, const BoxedValue& targetValue, const char* memberName, BoxedValue& outValue)
{
    outValue = BoxedValue();

    if (!targetValue.IsValid())
    {
        return false;
    }

    const Handle<ObjectBase>& object = GetObject(targetValue);

    if (!object)
    {
        return false;
    }

    const Class* cls = object.ptr->InstanceClass();
    Assert(cls != nullptr);

    IMember* member = cls->GetMember(StringHash(memberName));

    if (!member)
    {
        return false;
    }

    if (member->GetMemberType() == MemberType::Field)
    {
        Field* field = static_cast<Field*>(member);

        outValue = MakeValue(field->Get(targetValue));

        return true;
    }

    if (member->GetMemberType() == MemberType::Method)
    {
        Method* method = static_cast<Method*>(member);

        ScriptObjectData data;

        if (method->IsScriptFunction())
        {
            Assert(method->GetParameters().Size() <= UINT8_MAX);

            data.type = ScriptObjectData::Type::ScriptFunction;
            data.func.m_addr = method->GetScriptAddress();
            data.func.m_nargs = (uint8)method->GetParameters().Size();
            data.func.m_flags = (uint8)method->GetFlags();
        }
        else
        {
            data.type = ScriptObjectData::Type::NativeFunction;
            data.nativeFunc = method;
        }

        outValue = MakeValue(data);

        return true;
    }

    return false;
}

bool HypScript::SetField(BoxedValue& targetValue, const char* memberName, BoxedValue&& value)
{
    if (!targetValue.IsValid())
    {
        return false;
    }

    const Handle<ObjectBase>& object = GetObject(targetValue);

    if (!object)
    {
        return false;
    }

    const Class* cls = object.ptr->InstanceClass();
    Assert(cls != nullptr);

    Field* field = cls->GetField(StringHash(memberName));

    if (!field)
    {
        return false;
    }

    field->Set(targetValue, std::move(value));

    return true;
}

bool HypScript::GetFunctionHandle(ScriptInstance* instance, const char* name, BoxedValue& outValue)
{
    outValue = BoxedValue();

    BoxedValue* value;
    if (!instance->exportedSymbols.Find(HashCode::GetHashCode(name).Value(), value))
    {
        return false;
    }

    if (!IsFunction(*value))
    {
        return false;
    }

    outValue = *value;

    return true;
}

bool HypScript::GetExportedValue(ScriptInstance* instance, const char* name, BoxedValue& outValue, bool getReference)
{
    outValue = BoxedValue();

    BoxedValue* value;
    if (!instance->exportedSymbols.Find(HashCode::GetHashCode(name).Value(), value))
    {
        return false;
    }

    Assert(value != nullptr);
    value = Deref(*value);

    if (getReference || ShouldValuePassByRef(*value))
    {
        outValue = MakeRef(value);

        return true;
    }

    outValue = *value;

    return true;
}

SymbolTable& HypScript::GetExportedSymbols(ScriptInstance* instance) const
{
    return instance->exportedSymbols;
}

} // namespace Hyperion
